### ISSUE TITLE
320 MB of IPCH files is being shipped

### ISSUE THREAD

**Issue by sean-mcmanus** [jeff-hykin/cpp-textmate-grammar#103]
@jeff-hykin I just noticed that this extension in unintentionally shipping the .vscode/IPCH folder created by our C/C++ extension. You should make sure those files are not getting published with your .vsix. The binary files contain the parsed contents of the header files.

**Comment by jeff-hykin** [comment]
Wow thats embarrassing 😅 thanks for pointing this out though. Change is merged in and published with `v1.8.3`
