### ISSUE TITLE
consideration for commit 898352f to be reverted

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#105]
This issue is for considering reverting commit https://github.com/jeff-hykin/cpp-textmate-grammar/commit/898352f4943ffebb3f47157d03df57a90a33e2e8

* This commit broke objective c++

1.7.7 | 1.8.2
-------|-------
| ![Screenshot from 2019-04-17 12-19-08](https://user-images.githubusercontent.com/714007/56315102-bde5cf80-610b-11e9-9834-9ce0202c0a4a.png) | ![Screenshot from 2019-04-17 12-18-59](https://user-images.githubusercontent.com/714007/56315108-c2aa8380-610b-11e9-879e-0e0320c4c311.png) |

* c++ embedded in markdown was already broken in atom/language-c
(vscode 1.33.1 no better C++)
![Screenshot from 2019-04-17 12-27-19](https://user-images.githubusercontent.com/714007/56315315-39e01780-610c-11e9-98a2-aa4e684db59d.png)

* this commit was not the best way to do it.

**Comment by jeff-hykin** [comment]
Did a temp manual revert of this, thanks for pointing this out.
