### ISSUE TITLE
inconsistent colorization of class and classes in templates

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#106]
Example code:
```c++
template <bool check = !Identity, class = std::enable_if_t<check>>
result_type operator()(argument_type k) {
}
template<class A, class B = C, typename D = E>
```
`class` on line 1 has the scope `entity.name.type.template.cpp`
`C` and `E`  on line 2 have the scope `storage.type.template.argument.C.cpp`

Image:
![Screenshot from 2019-04-17 16-03-26](https://user-images.githubusercontent.com/714007/56326314-5db25600-612a-11e9-81f2-638b1c4fe3df.png)

**Comment by jeff-hykin** [comment]
closing in favor of #246
