### ISSUE TITLE
C and C++ syntax highlight grammar doesn't support multiline comment and asterisk

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#11]
_From @Yanpas on February 15, 2019 14:11_

- VSCode Version: 1.31.1
- OS Version: linux

Steps to Reproduce:

1. Insert:
```c
bool aaaa(const char */* comment */) { return true; }
```
Result:
![image](https://user-images.githubusercontent.com/7345761/52861792-a0fd4200-3144-11e9-98f9-8462ac6f8d10.png)

No matter if you have any c/c++ extensions installed

Does this issue occur when all extensions are disabled?: Yes/No

_Copied from original issue: Microsoft/vscode#68784_

**Comment by alexr00** [comment]
We're going to try moving to a new C grammar soon. Once the move is done I'll see if this still reproduces.

**Comment by alexr00** [comment]
Looks like this one is still occuring moving to jeff-hykin/cpp-textmate-grammar.

**Comment by jeff-hykin** [comment]
Alright version 1.4.7 (pushed just now) should fix this. Let me know if it still persists though.
I also improved the parameter highlighting since it wasn't originally made to handle c-style comments inside of the definition.

**Comment by jeff-hykin** [comment]
Also thanks for moving this here @alexr00, I still haven't had a chance to look through the atom/c issues.

**Comment by alexr00** [comment]
Sure thing. Any time I get a C or C++ grammar issue I'll move it here :)
