### ISSUE TITLE
the colon of default case of switch missing parse.

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#110]
![image](https://user-images.githubusercontent.com/10380828/56456166-18e12600-639b-11e9-80b6-5d00cdc951b0.png)
maybe `punctuation.separator.default.cpp` useful.

**Comment by matter123** [comment]
Turns out the colon for default already had a pattern to match it, but it was not being used.

**Comment by matter123** [comment]
Fixed in v1.8.6
