### ISSUE TITLE
have textmate_tools automatically insert .maybe(@spaces) between patterns

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#111]
There are currently 52 places in `cpp/generate.rb` where `.maybe(@spaces)` is a part of a pattern.

This compiles https://godbolt.org/z/CE0ndD but currently, the grammar is sensitive to some of the spaces in it. 
![Screenshot from 2019-04-20 10-09-38](https://user-images.githubusercontent.com/714007/56460240-72723200-6354-11e9-842d-0e03280c189a.png). There are still many more places where optional spaces need to be added. 

The optional spaces are just visual noise that hurt the overall understandability of the patterns. Most patterns should not be affected by this change, and for the rare pattern that absolutely needs its there can be a `.thenNoSpace(`.

This would not apply to `.or(` so the common pattern `/a/.or(/b/)` would not be affected. There could additionally be an optimization that if a pattern starts or ends with `\s*` then the optional space is not added.

**Comment by jeff-hykin** [comment]
Hmm this is an interesting idea, I'll have to give it some thought and play around with things. I definitely want to make interesting changes like this to make things more intuitive, although normally I fall on the side of being explicit/readable over implicit and probably-what-you-intended. 

It is easy to figure out how to match one more thing. But it's hard/frustrating to figure out how to stop matching something that you're not explicitly matching.

**Comment by matter123** [comment]
The `\s*` could instead be `\s*?`. This should prevent the optional space from affecting patterns that check for a required space. Imagine `newPattern(/enum/.maybe(then(@spaces).then(/class/)))`. 

One place in particular where implicit spaces would be harmful is in the numeric_numeral pattern.

**Comment by jeff-hykin** [comment]
While I don't think we should implicitly include them, what do you think about creating a `@std_space` pattern that is lazy whitespace along with inline comments and anything else (maybe [[attributes]]) that are nearly always allowed inside of whitespace.

We could even make the pattern so that it would match a word boundary as well for things like `name{`

**Comment by matter123** [comment]
That sounds good. Attributes probably shouldn't be a part of `@std_space` as while they are allowed in quite a few places, they are not allowed everywhere. `void abort[[noreturn]]();` isn't valid for instance.

It seems this is modeling translation stage 1, which does (iirc)
- whitespace removal
- comment removal
- string combining (not applicable here)
- trigraph replacement (not applicable here)

Spaces and block comments should cover it.

**Comment by jeff-hykin** [comment]
Okay I pushed a `std_space` pattern that handles the spaces and block comments, it also works for cases like `namespace{` where there is only a word boundary. 

I didn't start using it everywhere, I'll leave that to another day.
