### ISSUE TITLE
Syntax highlighting issue within C macros

### ISSUE THREAD

**Issue by tristan957** [jeff-hykin/cpp-textmate-grammar#118]
This was not a problem at least in version 1.8.4.

![image](https://user-images.githubusercontent.com/11936772/56547725-de66bd00-6543-11e9-987b-842f04779f9a.png)

**Comment by matter123** [comment]
for copy/paste

```C
#include <glib-object.h>

#include "tllt-cp-cooking-details-dto.h"

G_DEFINE_TYPE(TlltCpCookingDetailsDto, tllt_cp_cooking_details_dto, G_TYPE_OBJECT);
```

**Comment by tristan957** [comment]
I'll be sure to add the text next time. My bad

**Comment by matter123** [comment]
vscode-textmate's inspect
https://gist.github.com/matter123/9a11416fca7a69d9b4fd64ed77fcf328

**Comment by tristan957** [comment]
This is not just a problem with macros. This is a problem with the first character of the first param of the function call

**Comment by matter123** [comment]
Yep, probably a parameter on line 75 of c/generate.rb looks behind it for a type, so it skips the first character

**Comment by matter123** [comment]
Not entirely sure why this just appeared with v1.8.6 as the bug existed before then but #119, when merged, should fix it.

**Comment by jeff-hykin** [comment]
pushed with `v1.8.7`. That is strange it didn't show up until after v1.8.4. I changed a lot with the underlying grammar tools today, but I didn't really change the patterns for C.

**Comment by tristan957** [comment]
@jeff-hykin could you guys start publishing the .vsix files on the releases tab?
