### ISSUE TITLE
true, false, and NULL in C++ are not highlighted

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#123]
Are you guys noticing that true, false, and NULL in C++ are not highlighted the same as in C?

_Originally posted by @tristan957 in https://github.com/jeff-hykin/cpp-textmate-grammar/issues/70#issuecomment-486048708_

**Comment by tristan957** [comment]
Might wanna add nullptr to this list

**Comment by matter123** [comment]
the pattern `constants` was partially renamed to `language_constants`, but It wasn't complete.

**Comment by jeff-hykin** [comment]
fixed in `v1.8.8`, pushed just now
