### ISSUE TITLE
have grammar check at the end to make sure that all of the included repository_names are actually valid repo names

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#125]
Making a separate issue to track this.

This TODO would have prevented #123.

**Comment by jeff-hykin** [comment]
Pushed an initial fix for this on master. But this only works for :$initial_context.

Its going to be a lot more work to check the names of all the pattern's/ranges #includes because we have to wait until the grammar is being exported before checking.
