### ISSUE TITLE
function parameter highlighting improvements

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#134]
List of possible paramater syntaxes
```yaml
function_parameters:
    1: Type (*name)(:function_parameters) = Value
    2: Type (*)(:function_parameters) = Value
    3: Type name = Value
    4: Type = Value
    5: Type (*name)(:function_parameters)
    6: Type (*)(:function_parameters)
    7: Type name
    8: Type
    9: <empty>
```

currently, the support is rather poor.
the variable is correctly identified in cases 1,3,5, and 7.
in cases 1,2,5, and 6, the return type of the function pointers is tagged as a function.
in case 4 the type is marked as the variable.
no cases mark the default value.

#71 fixes case 3 and 7.

**Comment by matter123** [comment]
The eventual PR I'll submit Saturday or Sunday should include: this, function pointers, and #71 applied to class/struct definitions as all three are interrelated.

**Comment by matter123** [comment]
From the `Explore-#71` branch
![Screenshot from 2019-04-26 20-02-14](https://user-images.githubusercontent.com/714007/56844044-f9487280-685e-11e9-9611-e6c60d2ce917.png)

**Comment by matter123** [comment]
Is there any issue with adding support for comments, and string/numeric/language constants to the list of parameters and using it for both function definitions and function calls? It could be a generator so that inside a function foo(a,b,c) highlights a, b, and c as a variable but outside a function as a type.

**Comment by jeff-hykin** [comment]
I think next time I work on the parameters I'll make a pattern for defaulted parameters.
If its a PatternRange, with a start of `=` and an end of lookAhead for `,` or `)` I think it can include all of the expresson_context patterns in a really solid way.

I think the pattern could also be applied to the template evaluative context too (e.g. `template<class B = C>`)

**Comment by matter123** [comment]
Closing as this is fixed in master.

![Screenshot from 2019-06-22 19-42-25](https://user-images.githubusercontent.com/714007/59970886-e16f3100-9525-11e9-8d6e-8b1435dd7f00.png)

**Comment by jeff-hykin** [comment]
Alright all those cases and more (whenever there was an array) were fixed.
