### ISSUE TITLE
function for a specific type after insertion operator

### ISSUE THREAD

**Issue by sykoram** [jeff-hykin/cpp-textmate-grammar#141]
![image](https://user-images.githubusercontent.com/41990490/57177712-4f24a800-6e67-11e9-8ec3-945c85aea25b.png)
cout is highlighted as a function,
max as a type

**Comment by matter123** [comment]
For copy/paste
```c++
void func() {
	std::cout << max<int>(a, b) << std::endl;
	std::cout << max(a, b) << std::endl;
}
```

**Comment by matter123** [comment]
the fist line was parsed as `std::cout< <max<int >(a,b)`, that is, a templated function call to cout.

**Comment by jeff-hykin** [comment]
Merged in the fix for this, and it should get pushed later tonight. 👍
