### ISSUE TITLE
regression in anonmyous enum

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#146]
It looks like #144 caused a regression.

code:
```c++
enum{};
```
Image:
<img width="74" alt="Screen Shot 2019-05-06 at 10 16 39" src="https://user-images.githubusercontent.com/714007/57242398-3b547f80-6fe8-11e9-8177-8ab9128ed2c1.png">

**Comment by jeff-hykin** [comment]
I think this was fixed in one of the last few versions.
