### ISSUE TITLE
Space between class access specifier and colon

### ISSUE THREAD

**Issue by ember91** [jeff-hykin/cpp-textmate-grammar#15]
**Describe the bug**
- OS and Version: Ubuntu 18.04.2 LTS
- VS Code Version: 1.31.1
- Better C++ Syntax Extension Version: 1.4.13
- Other extensions you installed (and if the issue persists after disabling them): C/C++. The issue persists after disabling it.
- A clear and concise description of what the bug is: When adding a space between a class access specifier, such as 'public', and the colon, the access specifier loses its coloring.

**To Reproduce**
1. Create a new file with extension '.cpp'.
2. Input the code below in the newly created file. 
```
class C
{
  public :
};
```
3. Try removing the space between 'public' and ':'. The keyword should be colored.

**Expected behavior**
The keyword shall be colored regardless of space between the keyword and colon. 

**Screenshots**
![Screenshot from 2019-03-11 17-12-48](https://user-images.githubusercontent.com/31469580/54139486-f36b0f00-4421-11e9-95b7-a71266ba030b.png)

**Additional context**
This issue exists with default VS code highlighting as well. I'm not sure if it's syntactically correct, but it compiles on GCC/clang.

**Comment by jeff-hykin** [comment]
Coded a fix for this and I'll push it with the next update. 👍

**Comment by jeff-hykin** [comment]
Fixed is pushed with v1.5.0
