### ISSUE TITLE
backreferences do not work in start_pattern or end_pattern

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#163]
while backreferences work for the unit tests. The generated regex in the json file still contains `[:backreference:...:]`. See https://github.com/jeff-hykin/cpp-textmate-grammar/blob/Fix/%2380/syntaxes/cpp.tmLanguage.json#L1246

**Comment by matter123** [comment]
on Line 871 and 885, you set `:begin` and `:end` for the tag without calling `#to_tag` this causes back-references to not be fixed up when using a `PatternRange`

**Comment by jeff-hykin** [comment]
Thanks for looking into this, it's probably going to be 2 days before I can get code merged in
