### ISSUE TITLE
no scope resolultion when specifying base class

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#166]
![image](https://user-images.githubusercontent.com/10380828/57732585-feffde00-76cf-11e9-86fd-abcac71d1bc2.png)
https://github.com/lhmouse/asteria/blob/d1fba75d4e2cc42dc234913c2eca8b8daeaf4309/asteria/src/utilities.hpp#L131

**Comment by matter123** [comment]
![Screenshot from 2019-05-14 15-29-45](https://user-images.githubusercontent.com/714007/57736523-26699300-765d-11e9-9daf-55b7135c13ee.png)

This should be fixed when #167 is merged in. About 2 days or so.

**Comment by jeff-hykin** [comment]
Thanks matter123 👍
