### ISSUE TITLE
scoped enum names not highlighted when refering to enums

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#168]
Originally reported in #55.

<img width="596" alt="Screen Shot 2019-05-15 at 12 43 58" src="https://user-images.githubusercontent.com/714007/57804315-3d68bd80-770f-11e9-9c6e-bfb2edb67253.png">

c++11 <sup>[1]</sup> allows for opaque enum declarations to have a nested scope.

[1] https://en.cppreference.com/w/cpp/language/enum (see declaration form 2)

**Comment by jeff-hykin** [comment]
fixed with `v1.12.0`
