### ISSUE TITLE
universal-charcter-names not allowed in identifiers

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#17]
According to the standard identifiers are allowed to contain universal-character-names ([lex.name]/1).
Universal-character-names are of the the pattern `/\\u[0-9a-fA-F]{4}/` or `/\\U[0-9a-fA-F{8}/`. When these characters are inserted into a place where identifiers are expected highlighting breaks.

![Screenshot from 2019-03-12 11-14-12](https://user-images.githubusercontent.com/714007/54225014-fdd7e800-44b7-11e9-9bb9-cda8d6242378.png)

**Comment by jeff-hykin** [comment]
If that syntax is truly allowed everywhere its going to take awhile to get it tracked down.

The good news is a lot of the code already depends on `variable_name` or `variable_name_without_bounds`, once all of the legacy syntax is moved to using `variable_name` or `variable_name_without_bounds` this issue can be fixed pretty easily.

**Comment by jeff-hykin** [comment]
The merge for this broke things so I manually reverted.

**Comment by jeff-hykin** [comment]
pushed with `v1.8.0`
