### ISSUE TITLE
Scope resolution is not part of a function's name

### ISSUE THREAD

**Issue by alekseyt** [jeff-hykin/cpp-textmate-grammar#179]
Hello. This is a question related to vscode 1.34.

I'm trying to make a theme for C++ and i don't quite like that `std` in `std::string` is highlighted, so i'm trying to disable specifically namespaces highlighting. Example:

![image](https://user-images.githubusercontent.com/993454/58034190-a47edb80-7b2e-11e9-81c4-1c462273a475.png)

The problem i'm facing is that i can't disable namespaces highlighting separately from class members definition or vice versa. This is what happens when i'm trying to disable highlight:

![image](https://user-images.githubusercontent.com/993454/58034403-30910300-7b2f-11e9-84c8-d949d34de660.png)

Is there a way to do separate highlighting for 1) member definition/static calls and 2) actual namespaces?

If i recall correctly, `base::f` was considered as a whole before if it's a function call as in `base::f(s);` or a definition as in `base::f(...) {}`, and was highlighted uniformly, but i might be wrong. I can't find relevant section in `cpp.tmLanguage.json`. Any suggestions?

**Comment by matter123** [comment]
That scope should be `entity.name.type.namespace.scope-resolution`

**Comment by matter123** [comment]
One workaround would be to style `meta.function.definition.parameters.cpp entity.name.type.namespace.scope-resolution.cpp` the same as your text color. That should disable scope resolution highlighting only in function parameters.

**Comment by alekseyt** [comment]
Thank you. I've got the `entity.name.type.namespace.scope-resolution` part and tried to work this around by setting namespace color to function call color and it worked fine.

After fiddling with this i'm not entirely sure if this is strictly speaking a bug because in case of something like `glm::normalize(...)`, `glm` is the namespace and `normalize()` is a function call. So in that case it is colored correctly, but in case of member definition as in `void base::f() {}`, `base` isn't really namespace, but it's kinda OK.

It would be nice to remove color from `std` in `std::string`, but it's not a big deal really.

However i noticed that C++17 nested namespaces are affected too:

![image](https://user-images.githubusercontent.com/993454/58043234-545f4380-7b45-11e9-826c-222d5e8389b2.png)

All this looks like different issues to me and i wouldn't want to mix all this in one issue. If it's OK i would close this issue. My question was answered and it looks OK-ish, i can live with this.

**Comment by matter123** [comment]
![Screenshot from 2019-05-20 11-37-04](https://user-images.githubusercontent.com/714007/58044042-a4151f00-7af3-11e9-91a8-87db97c17117.png)
```
{
	"name": "foo",
	"scope": "meta.function.definition.parameters.cpp entity.name.type.namespace.scope-resolution.cpp",
	"settings": {
		"foreground": "#bbbbbbff"
	}
},
{
	"name": "foo",
	"scope": "meta.function.definition.parameters.cpp punctuation.separator.namespace.access.cpp",
	"settings": {
		"foreground": "#bbbbbbff"
	}
}
```

**Comment by matter123** [comment]
And despite that `glm` in `glm::normalize(...)` is a namespace, the function name is still `glm::normalize` its just qualified.

**Comment by alekseyt** [comment]
`meta.function.definition.parameters.cpp entity.name.type.namespace.scope-resolution.cpp`

I understand how this works, but it removes namespace highlighting only from function arguments leaving it in member and non-member declarations:

![image](https://user-images.githubusercontent.com/993454/58045684-da7e8880-7b4b-11e9-8858-414728ef2efb.png)

And due to previous workaround, i have to keep "broad" `entity.name.type.namespace.scope-resolution` to highlight `base` in `base::f() {}` and it highlights other bits. I tried to look into syntax file to see if i can discolor namespaces but assign color to `base` specifically in member definition but couldn't find it.

This is fine. Highlighting namespaces (or rather scopes i guess) isn't bad thing. This is just FYI, just food for thoughts, maybe syntax could be improved in one way or another.

I think this issue can be closed now since my question was fully answered. I can file other issues for what you consider a bug.

**Comment by matter123** [comment]
Yeah, The syntax definitely needs more scopes.

The test in `namespace test::nested {` could be marked with `meta.head.namesace.cpp entity.name.type.namespace.scope-resolution.cpp`. So the fact that namespace does not have `meta.head.namespace.cpp` is a bug.

`std::string &s` highlighting is being tracked at #71 and parameter highlighting at #134. So, you might want to subscribe to those.

**Comment by alekseyt** [comment]
I'm closing this one then, i'm pretty happy with the workaround. Thank you very much.
