### ISSUE TITLE
Object members highlighting

### ISSUE THREAD

**Issue by alekseyt** [jeff-hykin/cpp-textmate-grammar#180]
This is a question related to vscode 1.34.

I'm trying to highlight class/struct members like this:

![image](https://user-images.githubusercontent.com/993454/58036505-f0804f00-7b33-11e9-8f57-f5e19ca2a3b5.png)

I'm tried to highlight `variable.other.object` and this kind of works, but it highlights part i didn't want to highlight:

![image](https://user-images.githubusercontent.com/993454/58036635-3dfcbc00-7b34-11e9-93cc-874ac68defb7.png)

Is there a way to separately highlight object and its members?

Thanks.

**Comment by matter123** [comment]
See #59 in particular https://github.com/jeff-hykin/cpp-textmate-grammar/issues/59#issuecomment-481918973

**Comment by jeff-hykin** [comment]
Here's what you can do. 
`variable.other.object.access` // should tags the first word
 `variable.other.object.property` // should tag the middle words
`variable.other.property` // should tag the last word

If that isn't the case (I'll check at home) then something needs to be fixed.

**Comment by alekseyt** [comment]
Thank you, i had moderate success with `variable.other.object.property`:

![image](https://user-images.githubusercontent.com/993454/58042384-3bee2980-7b43-11e9-8a28-5d056b5d5250.png)

It does that, but surprisingly it highlights `z->` entirely (or `z.` if that matters). I've read comments in #59 and tried to override color for `punctuation.separator.pointer-access.cpp` or even `punctuation.separator`, but it doesn't seem to help. I suspect maybe `->` is being captured with `z` or something, not sure about this.

Maybe this is already fixed, apparently syntax file was already updated in vscode's master and revision in 1.34 might be somewhat old. I replaced it from master and it fixed some other issues i've seen in 1.34, but not this one. But `variable.other.object.property` definitely seems like a way to go.

**Comment by matter123** [comment]
That's #130. I'll try to get a PR for it in the next 12 hours.

**Comment by alekseyt** [comment]
I'm closing this as a duplicate then. Thank you very much.
