### ISSUE TITLE
Provide way to "re-tag" patterns.

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#181]
The currently correct way to re-tag a pattern is `.without_numbered_capture_groups` however, this only provides a way to re-tag capture group 0, if one wants to re-tag a different capture group the pattern needs to be duplicated. Additionally, as #130 shows this re-tagging can sometimes grab too much.

I was thinking something like
```ruby
partial_member.reTag(
    "variable.other.object.access" => "variable.other.object.property"
)
```
where the key would be:
 1) an existing tag
 2) a group number
 3) or a reference

and the value is the new tag.

Existing tags that are left alone can either be dropped or can be carried through.

**Comment by jeff-hykin** [comment]
I think thats a good design.

When I originally worked on designing the library, I wanted a retagging feature but I couldn't think of a simple way to do it so I fell back on just wrapping them inside of functions.
