### ISSUE TITLE
Alternative operator representations (and, and_eq, bitand) support

### ISSUE THREAD

**Issue by Yanpas** [jeff-hykin/cpp-textmate-grammar#19]
Currently there is no special coloring for these keywords: https://en.cppreference.com/w/cpp/language/operator_alternative

and, and_eq, bitand, bitor, compl etc.

**Comment by jeff-hykin** [comment]
<img width="474" alt="Screen Shot 2019-03-13 at 11 49 12 AM" src="https://user-images.githubusercontent.com/17692058/54298063-11ea1b00-4586-11e9-812c-591ecd8ee848.png">

I think this might be an issue with your theme, as they are all correctly tagged/highlighted for me.

**Comment by jeff-hykin** [comment]
If it is a setting with your theme, you can probably fix the problem in 5 min yourself, just add the following to your settings.json.

```
        "editor.tokenColorCustomizations" : 
            {
                "textMateRules": [
                    // 
                    // Purple
                    // 
                        {
                            "name": "purple",
                            "scope": [
                                // name of the thing you want highlighted
                                "source.cpp keyword.operator",
                                ],
                            "settings": {
                                "foreground": "#c792eaff",  // change me to whatever you want
                                "fontStyle": ""
                            }
                        },
                ],
            },
