### ISSUE TITLE
function definition pattern matches inside function definition scope

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#193]
Example:
```c++
foo bar() {}
struct foo() {
	foo bar() {
		foo bar();
	}
};
```
![Screenshot from 2019-05-22 13-56-37](https://user-images.githubusercontent.com/714007/58208442-95686c80-7c99-11e9-8d6c-59147a85d92e.png)
The bar on line 4 cannot be a function definition as functions are not allowed to be nested. bar is rather a default constructed foo object.

**Comment by jeff-hykin** [comment]
Thats really strange. The function definition pattern includes the `:function_call` before the `:$initial_context` so it should give it higher priority. For some reason it doesn't though (removing the $initial_context allows the function call to match)

**Comment by matter123** [comment]
it's the best match rule. with function definition now matching the type. the function definition matches earlier in the line than the function call witch matches at `bar` See https://github.com/jeff-hykin/cpp-textmate-grammar/blob/master/test/src/pattern-coverage/onigScanner.js#L49

**Comment by jeff-hykin** [comment]
Well I guess now is as good a time as ever to create a pattern for a default constructed object.

**Comment by jeff-hykin** [comment]
That or we could try to figure out a $initial_context solution. The problem being that we can't just use a different scope entirely because it will probably break other syntaxes like Objective C++

**Comment by matter123** [comment]
This is a relatively minor issue as per #36 bar would have already been marked as a function. This should resolve itself as #81, #138, and contexts are resolved.

**Comment by matter123** [comment]
`foo * bar()` where foo is a variable and bar is a function call causes `foo *` to be as a type that is a pointer to foo. See #204
