### ISSUE TITLE
const no longer marked as keyword in function parameter

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#194]
![Screenshot from 2019-05-22 14-31-03](https://user-images.githubusercontent.com/714007/58213851-8210cd80-7ca8-11e9-862b-2d12cd3cd27b.png)

**Comment by jeff-hykin** [comment]
v1.9.0 fixes the const problem, but it breaks something else
<img width="828" alt="Screen Shot 2019-05-23 at 1 39 17 AM" src="https://user-images.githubusercontent.com/17692058/58228129-9b8f3500-7cfb-11e9-8153-a81a92bd33a4.png">

**Comment by jeff-hykin** [comment]
fixed with `v1.9.2`
