### ISSUE TITLE
conversion operators for non fundemntal types are colored incorrectly.

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#2]
Conversion operators for user-defined or qualified fundamental types are not colored correctly.
See:
![screenshot from 2019-02-10 14-21-45](https://user-images.githubusercontent.com/714007/52540557-ae2ec100-2d3f-11e9-855d-0b9ca8e35bcb.png)

TM Grammer inspection of a incorrectly colored operator
![screenshot from 2019-02-10 14-24-44](https://user-images.githubusercontent.com/714007/52540572-f51cb680-2d3f-11e9-9e46-0e2a7cbf3af0.png)

TM Grammer inspection of a correctly colored operator
![screenshot from 2019-02-10 14-24-54](https://user-images.githubusercontent.com/714007/52540576-fe0d8800-2d3f-11e9-95f3-c28b0488f20b.png)

**Comment by jeff-hykin** [comment]
Alright that should be fixed! Just update to `1.3.1`. Thanks for pointing this out
