### ISSUE TITLE
Comments after function in the same line not highlighted

### ISSUE THREAD

**Issue by WEGFan** [jeff-hykin/cpp-textmate-grammar#203]
VS Code version: 1.34.0
Extension version: 1.9.0 ~ 1.9.5

Sample Code
```cpp
// another comment
int fun() /* a comment */ // test
{
    return 1; /* a comment */ // test
}
```
![Snipaste_2019-05-26_00-46-46](https://user-images.githubusercontent.com/7558201/58372456-ffaa3700-7f4f-11e9-8dab-644873941453.png)

**Comment by jeff-hykin** [comment]
Thanks for pointing this out. The fix is pushed in `v1.9.6`. Let me know if its still an issue
