### ISSUE TITLE
Functions highlighting

### ISSUE THREAD

**Issue by alekseyt** [jeff-hykin/cpp-textmate-grammar#206]
I was fiddling with syntax highlighting on latest master and found this example:

```c++
glm::normalize(glm::vec3(1));
```

![image](https://user-images.githubusercontent.com/993454/58374683-fd91a980-7f4a-11e9-8de2-8e8c14861f58.png)

My settings are: 

* `entity.name.scope-resolution` isn't highlighted (white)
* `entity.name.scope-resolution.function` highlighted green

However `glm::vec3()` is highlighted green wholly while in `glm::normalize()` only `normalize()` is highlighted. I'm not sure which one is a bug, or maybe i'm doing something wrong in theme settings.

Just a side note: if you would use `entity.name.function` to mark functions, existing themes for vscode might pick this up automatically.

**Comment by matter123** [comment]
functions are marked as `entity.name.function.{definition,call}`

I can't seem to reproduce.

Have you published your theme?

![Screenshot from 2019-05-25 14-23-32](https://user-images.githubusercontent.com/714007/58374780-c85c6b80-7ef8-11e9-902c-3ee2a0f98378.png)

**Comment by alekseyt** [comment]
No, i haven't published it, but i think in your theme you have highlighting set for broader `entity.name.scope-resolution` but don't have highlighting for narrower `entity.name.scope-resolution.function`.

If you have `entity.name.function` in your theme then it won't work on `glm::vec3(1)`, but `entity.name.scope-resolution.function` will.

```shell
$ cat cpp.tmLanguage.json | grep entity.name.scope-resolution.
          "name": "entity.name.scope-resolution.cpp"
          "name": "entity.name.scope-resolution.template.call.cpp"
          "name": "entity.name.scope-resolution.template.definition.cpp"
          "name": "entity.name.scope-resolution.function.call.cpp"
          "name": "entity.name.scope-resolution.function.definition.cpp"
          "name": "entity.name.scope-resolution.namespace.alias.cpp"
          "name": "entity.name.scope-resolution.namespace.using.cpp"
          "name": "entity.name.scope-resolution.namespace.block.cpp"
          "name": "entity.name.scope-resolution.function.definition.operator-overload.cpp"
          "name": "entity.name.scope-resolution.cpp"
          "name": "entity.name.scope-resolution.cpp"
          "name": "entity.name.scope-resolution.cpp"
          "name": "entity.name.scope-resolution.cpp"
          "name": "entity.name.scope-resolution.cpp"
          "name": "entity.name.scope-resolution.cpp"
```

Note `"name": "entity.name.scope-resolution.function.call.cpp"` and `"name": "entity.name.scope-resolution.function.definition.cpp"`.

Here is the theme where it's reproducible anyways: [theme.zip](https://github.com/jeff-hykin/cpp-textmate-grammar/files/3219772/theme.zip)

**Comment by matter123** [comment]
Ok so if I understand you, the issue is that scope resolution is not part of the `entity.name.function`?

**Comment by alekseyt** [comment]
Well, i thought that issue might be that `glm::normalize()` isn't a function, another example is:

```c++
glm::normalize(glm::normalize(v));
```
which is highlighted differently if i use `entity.name.scope-resolution.function`. I would like to use whole function highlighting in the theme, but i'm not sure what am i doing wrong or if this is even supported. I don't insist that this is a bug, but it looks inconsistent.

`entity.name.scope-resolution.function` is also tagging function declarations like `void base::f() {}` to highlight `base` so i though i'll ask.

**Comment by matter123** [comment]
So `base` in `void base::f() {}` has the scope `entity.name.scope-resolution.function.definition.cpp` that should allow distringuishing function calls and function definitions

**Comment by alekseyt** [comment]
I see. This works too. Thank you very much.
