### ISSUE TITLE
someting about overload and others.

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#207]
![image](https://user-images.githubusercontent.com/10380828/58396645-2a93a880-8080-11e9-8083-705830dd6b37.png)

![01](https://user-images.githubusercontent.com/10380828/58396981-8874c000-8081-11e9-9329-de6a3546b2fa.png)

https://github.com/lhmouse/asteria/blob/master/asteria/src/rocket/cow_string.cpp

**Comment by jeff-hykin** [comment]
The original issue causing this has been fixed, however a new bug blocked/caused by #219 has broken the code in a new way. I'm going to close this issue in favor of #219
