### ISSUE TITLE
feature request : Predefined Macros

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#210]
MSVC
https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019

GCC
https://gcc.gnu.org/onlinedocs/cpp/Predefined-Macros.html#Predefined-Macros

Clang
https://clang.llvm.org/docs/LanguageExtensions.html

At sourceforge for gcc and maybe msvc
https://sourceforge.net/p/predef/wiki/Home/

and how to list them:
http://nadeausoftware.com/articles/2011/12/c_c_tip_how_list_compiler_predefined_macros

really a big work. 
but we often use a little of them.

**Comment by matter123** [comment]
Are you looking for tagging like `entity.nane.other.preprocessor.macro.predefined.__gnu__.cpp`? Or something more?

**Comment by peaceshi** [comment]
> Are you looking for tagging like `entity.name.other.preprocessor.macro.predefined.__gnu__.cpp`? Or something more?

opps,,
maybe it is a bug here... others is fine.
![image](https://user-images.githubusercontent.com/10380828/58402936-0b067b00-8094-11e9-9371-021a4ad984b4.png)

**Comment by jeff-hykin** [comment]
This should be pretty easy to add so long as its just a list of names. Hopefully we can add it in the next few releases, although we do have some big challenges like breaking most of the objective-C++ syntax that we need to work out first 😬

**Comment by matter123** [comment]
#212 only added predefined macro support to initial_context. It's not a complete fix.
![Screenshot from 2019-05-29 10-23-46](https://user-images.githubusercontent.com/714007/58577694-e200fa00-81fb-11e9-8a50-7d8b11e2cc0c.png)

**Comment by moe123** [comment]
Hello,

I would add to this: distinguishing user defined macro identifier, function identifier, builtin keywords (in term of color).

<img width="407" alt="Screen Shot 2019-05-31 at 17 41 42" src="https://user-images.githubusercontent.com/19998532/58741232-8ab18400-83cb-11e9-98ec-07bf534c0fb6.png">

**Comment by matter123** [comment]
the grammar has no way of knowing on lines 5,6, and 7 that expm1{,f,l} are macros. Textmate grammars parse on a line by line basis and most context is not kept between lines.

**Comment by jeff-hykin** [comment]
Fixed in `v1.12.0`
