### ISSUE TITLE
Small issue with function pointers in parameters

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/cpp-textmate-grammar#228]
<img width="394" alt="Screen Shot 2019-06-06 at 9 43 13 PM" src="https://user-images.githubusercontent.com/17692058/59078467-d8832c00-88a4-11e9-938b-d1126ee31019.png">
(The lower one is correct, I'm not sure why a space affects it)

**Comment by matter123** [comment]
The space effects it, because `qualified_type` matches spaces in the beginning, that makes it a better match than `storage_types`, but when there is no space `storage_types` is an earlier match, so that makes it a better match.

**Comment by jeff-hykin** [comment]
Pushed the fix just now
