### ISSUE TITLE
struct cannot be used as a part of a type cast.

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#230]
**From**:
https://github.com/microsoft/vscode-cpptools/issues/3741

**Description of Issue**:
When struct is a part of a type cast it does not close the struct head until the `;`.

**Possible Solution**:
Temporary:
 - Prevent the struct declaration pattern from being preceded by `(`
 - End the struct declaration at `)`

Permanent:
 - Prevent struct declarations from happening inside of the function definition context

**Example Code**:
```c++
void func()
{
    struct var** thing = (struct var**)func(); //comment
}
```
**Example image**:
![Screenshot from 2019-06-07 11-35-33](https://user-images.githubusercontent.com/714007/59125860-61877b00-8918-11e9-9893-989fe02f82ec.png)

**Comment by jeff-hykin** [comment]
Temp fix for this by including the parameter struct syntax inside of the () blocks. Probably need to make sure this is covered for enums/unions too before closing this issue.

**Comment by matter123** [comment]
Yeah there is an issue with class and union
![Screenshot from 2019-06-12 13-21-02](https://user-images.githubusercontent.com/714007/59383560-fc1afc00-8d14-11e9-80ae-7bae50bba695.png)

**Comment by jeff-hykin** [comment]
Alright this should be fully fixed with the latest change and should be pushed to the extension in the next day or so.
