### ISSUE TITLE
std_space should not require `@word_boundary`.

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#232]
Because `std_space` requires a word boundary it is not a drop-in replacement for `.maybe(@spaces)`. For example `( A` is matched by `/\(/.maybe(@spaces).then(/A/)` but not `/\(/.then(std_space).then(/A/)`

The correct behavior is:
 one or more of:
  - `@space`
  - `inline_comment`
  - `@word_boundary`

**Comment by jeff-hykin** [comment]
I agree 
`/\(/.then(std_space).then(/A/)` should match `( A`
should also match: 
`(A`
`(/*comment*/A`
`( /*comment*/A`
`(/*comment*/ A`
`( /*comment*/ A`
