### ISSUE TITLE
attributes before function definition no longer marked as such

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#239]
It looks like a regression since 1.11.5

![Screenshot from 2019-06-11 21-46-30](https://user-images.githubusercontent.com/714007/59324156-8cfcc380-8c92-11e9-8db6-b36469535f14.png)

Current tests are sufficient to catch this.

**Comment by jeff-hykin** [comment]
Thanks for catching this

**Comment by jeff-hykin** [comment]
alright pushed a fix 👍
