### ISSUE TITLE
Comments in namespace head tagged as namespace name

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#243]
All words are tagged as `entity.name.namespace`

Example:
```c++
namespace foo
// single line comment
/* multi
 line
 comment
*/
{
    
}
```

Image:
<img width="222" alt="Screen Shot 2019-06-15 at 20 19 21" src="https://user-images.githubusercontent.com/714007/59558618-09511880-8fab-11e9-9423-66114a1fee16.png">

**Comment by jeff-hykin** [comment]
Fix implemented on master, new version hasn't been pushed yet though
