### ISSUE TITLE
new parameter range breaks static assert.

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#247]
Example:
```
struct foo {
	static_assert(true, "foo");
	static_assert(bar, "bar");
	foo(){}
	int bar(foo bar);
};
```
![Screenshot from 2019-06-21 10-12-13](https://user-images.githubusercontent.com/714007/59939530-189def00-940d-11e9-9895-1760179b1bf9.png)

This causes issue for the rest of the items in the struct.

**Comment by jeff-hykin** [comment]
Thanks for catching and taking care of this @matter123
