### ISSUE TITLE
Function parameters on a newline

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/cpp-textmate-grammar#25]
https://github.com/atom/language-c/issues/118

Sadly this is just outside of the capabilities of TextMate grammars (as noted on the original issue)

**Comment by matter123** [comment]
Downgrading this to nearly impossible. The original issue said this was impossible because having a begin pattern that just matches `bool printStats` would be impractical. #135 implements such a pattern, so more investigation is needed.
