### ISSUE TITLE
Problems with syntax highlighting and unary scope operator (C++)

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#254]
Copied From: https://github.com/microsoft/vscode-textmate/issues/99

By @hassanbot

### Original Issue

Hi! I'm not 100% sure this is the correct place to put this issue, so please redirect me if it should be placed somewhere else and I'll open one there.

Anyway, I'm having problems with the syntax highlighting when using the unary scope operator (to indicate global scope or anonymous namespace). Details below!

    * VSCode Version: 1.35.1 (user setup)

    * OS Version: Windows 10 Professional 64 bit, Build 17763 (Windows_NT x64 10.0.17763)

Steps to Reproduce:
    1. Select the **Monokai** theme (though other themes probably work as well) through File -> Preferences -> Color Theme.
    2. Create a .cpp file with the following code:

```c++
#include <iostream>
#include <string>

namespace hello
{
    void saySomething(std::string text)
    {
        std::cout << text << std::endl;
    }
}

void saySomething(std::string text)
{
    std::cout << text << std::endl;
}

int main()
{
    hello::saySomething("Hello world");
    saySomething("Hello world");
    ::saySomething("Hello world");
    return 0;
}
```

**Expected syntax highlighting (in main function):**
Namespaces: Green with underline.
Function calls: Green.
Strings: Yellow(ish).
Parentheses: White.
Semicolons: White.
Scope operators (::): White.
 
**Resulting syntax highlighting:**
Same as expected, except that the last call, using the scope resolution operator to indicate global scope shows in all white (see picture).
![vscode_syntax_highlighting](https://user-images.githubusercontent.com/10755449/59835019-40c41a00-9349-11e9-81dd-e3e7b0bd9d84.PNG)

Using the TM Scope Inspector (Ctrl + Shift + P -> Developer: Inspect TM Scopes), the scopes for the first two calls to saySomething are:
**Scope operator**:
   * punctuation.separator.namespace.access.cpp
   * meta.scope-resolution.cpp
   * meta.block.cpp
   * source.cpp

**Function call**
   * entity.name.function.call.cpp
   * meta.function-call.cpp
   * meta.block.cpp
   * source.cpp
**Parentheses**
   * punctuation.section.arguments.[begin|end].bracket.round.cpp
   * meta.function-call.cpp
   * meta.block.cpp
   * source.cpp

**Strings**
   * string.quoted.double.cpp
   * meta.function-call.cpp
   * meta.block.cpp
   * source.cpp

**Semicolons**
   * punctuation.terminator.statement.cpp
   * meta.block.cpp
   * source.cpp

However, for the third call (`::saySomething`), the entire row (including scope operator, string, etc.) has the following scopes:
   * meta.function-call.cpp
   * meta.block.cpp
   * source.cpp

In addition to this, the closing curly bracket of the main function also gets this scope if the call to ::saySomething is present. Otherwise it gets this scope:
   * punctuation.section.block.end.bracket.curly.cpp
   * meta.block.cpp
   * source.cpp

**Comment by jeff-hykin** [comment]
I'll work on this before fixing the template syntax. And while I'm at it I'll clean up all of the `::` syntax into one or two straight forward patterns.

**Comment by matter123** [comment]
It looks like the reported issue has been fixed. However there seems to be some othe regressions.

`std` went from `entity.name.type.namespace.scope-resolution.cpp` to `entity.name.scope-resolution.cpp`
ditto for `hello` in `main`

the `hello` in namespace `hello` is because of namespaces no longer having `entity.name.type` Though im not sure why thats an issue as the monokai theme is based on the sublime text one and `hello` has the follow scopes in sublime text 3:
`source.c++ meta.namespace.c++ entity.name.namespace.c++`  
  
#### Image
vscode 1.35.1 | Better Syntax 1.11.17
--------------|----------------------
![Screenshot-20190623154817-352x442](https://user-images.githubusercontent.com/714007/59982951-80e7fe80-95ce-11e9-8efa-8f406898c7f4.png) | ![Screenshot-20190623154732-358x447](https://user-images.githubusercontent.com/714007/59982952-847b8580-95ce-11e9-8810-9483b9d58d3d.png)

**Comment by jeff-hykin** [comment]
Thats what I'd expect to be, although it is a shame the theme doesn't highlight `hello` in `namespace hello`.

**Comment by matter123** [comment]
Yeah because there should be support for that See https://github.com/microsoft/vscode/blob/master/extensions/theme-monokai/themes/monokai-color-theme.json#L208, maybe that change didn't make the 1.35.1 cut.
