### ISSUE TITLE
1.12.1 performance regression.

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#257]
![Screenshot from 2019-06-24 22-53-50](https://user-images.githubusercontent.com/714007/60072645-048b1380-96d3-11e9-8af2-1dbffb9de940.png)

line 3493 is `meta.function.definition`
line 4427 is `:function_call`
line 633 is `:source_wrapper`

~~Edit: possibly duplicate of #256~~
Edit: not fixed by #258

**Comment by jeff-hykin** [comment]
Crap what files are those showing up in?

**Comment by matter123** [comment]
It is one of my one files, Ill try to find a repro that is a more reasonable size.

**Comment by jeff-hykin** [comment]
if you're okay with it being open sourced, I dont think the size will be an issue if you want to add it to the testing examples

**Comment by matter123** [comment]
At least in the branch `Fix/#260`, `npm run perf` seems to show the issue. I'll create a PR for adding it to the examples in an hour or two.

**Comment by jeff-hykin** [comment]
After running perf I get something like
<img width="619" alt="Screen Shot 2019-06-26 at 5 09 30 PM" src="https://user-images.githubusercontent.com/17692058/60218535-3e742b00-9835-11e9-9ea8-7a8745211aa6.png">

How do I know what file that belongs to?

**Comment by matter123** [comment]
Unfortunately, that information is not recorded.

**Comment by jeff-hykin** [comment]
Ah haha well thats problematic, is there a way to program it in? or is restricted by a library

**Comment by matter123** [comment]
It's certainly possible, but currently the pattern timing recording doesn't distinguish between files.

**Comment by jeff-hykin** [comment]
Okay I'll work on adding that since I'm not sure how else to debug the slowdown

**Comment by matter123** [comment]
My best bet for how to add it would be have commands/perf inform the recorders on file change. And have a separate bin of records per file.

**Comment by matter123** [comment]
PR has been submitted with the file I originally ran perf on.

**Comment by jeff-hykin** [comment]
I created a very jank solution `npm run perfall` which takes about 10 minutes to run and outputs the performance metrics to a json file.

**Comment by matter123** [comment]
Fixed in v1.12.15.
