### ISSUE TITLE
Some comments cause vscode to hang since 1.11.6

### ISSUE THREAD

**Issue by scriptxotic** [jeff-hykin/cpp-textmate-grammar#260]
All in the title.
Small repro:

```cpp
// OK:
/********************* DATA *************************/
// Crash:
  /********************* DATA *************************/
```

**Comment by jeff-hykin** [comment]
I'll look into this today as well, @scriptxotic thanks for reporting this

**Comment by matter123** [comment]
After modifying perf to print the line before it tries that pattern it seems that the grammar gets stuck at 3943 or `meta.function.definition`

**Comment by jeff-hykin** [comment]
my guess is that this has to do with `std_space` being infront of so many patterns. Every inline comment in `std_space` involves backtracking, and with so many patterns starting with `std_space` its probably causing a backtracking explosion. I'm going to work on a fix related to that

**Comment by matter123** [comment]
The simplest fix would be to move the comment pattern near the top, right?

**Comment by jeff-hykin** [comment]
Yeah, I'm hoping that will solve the problem. I'm also going to try to make the inline comment pattern more efficient

**Comment by jeff-hykin** [comment]
@scriptxotic it should be fixed now in `v1.12.2` 

@matter123  I started adding the leading spaces but it didn't seem to be doing much and in some cases it was making the code incorrect. What I did instead that seems to have fixed it, is update the comment patterns and have the block comment consume the leading spaces. This makes the block comment take precedence over the other patterns that are trying to match an inline block comment. I also made the inline comment really efficient (no backtracking at all) but it actually didn't affect much either.

**Comment by matter123** [comment]
@jeff-hykin I rewrote the comment pattern in the branch Fix/#260. In particular I removed the nested  pattern ranges and made the banner patterns more generic. You might want to merge some of that in

**Comment by jeff-hykin** [comment]
Yup 👍 I'll do that

**Comment by scriptxotic** [comment]
Thank you! You two are doing a great job!
