### ISSUE TITLE
Indexing string literal breaks subsequent highlighting

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#264]
Original issue: https://github.com/microsoft/vscode/issues/76225#issue-461304759

BY @Dust1404
### Original Issue
VSCode Version: 1.35.1

![1](https://user-images.githubusercontent.com/40361332/60233860-b8a7bc80-98d4-11e9-977f-82e8547bec3d.PNG)
![2](https://user-images.githubusercontent.com/40361332/60233867-bcd3da00-98d4-11e9-86da-225bae28e0c7.PNG)

Just like the picture above. C++ syntax highlighting is broken after `""[]`.

I tried it on 4 different computers, wheter on Windows or Linux, whether with or without extensions.

I think it has nothing to do with the computer, system or extensions.

**Comment by jeff-hykin** [comment]
fixed in `v1.12.6`
