### ISSUE TITLE
explicit constexpr construct has missing scopes for `explicit`

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#268]
Example:
```c++
struct foo {
	explicit constexpr foo();
};
```

explicit does not have the scope `storage.modifier.specifier.functional.pre-parameters.explicit.cpp`. If constexpr is removed or if the constructor is made into a function explicit has the scope.

**Comment by jeff-hykin** [comment]
fixed with `v1.12.18`
