### ISSUE TITLE
The name of the Language is C++ not CPP

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#269]
The new icons in `/icons` are nice, however, c++'s icon has the text `CPP`. The language is `C++` and iconography reflects that. The ISO's official website for c++ has their logo with the text `c++` https://isocpp.org/. Generally, cpp should only be used when the plus sign is prohibited such as in the case of filename and identifiers. This is not the case in a logo.

**Comment by jeff-hykin** [comment]
Ah yeah don't worry, I was just testing if the autogeneration of the icons was working or not. 
This is the new icon I plan to keep:
<img width="585" alt="Microsoft VisualStudio Services Icons" src="https://user-images.githubusercontent.com/17692058/60393823-1a3c7680-9ae1-11e9-968d-f170bc42c253.png">
