### ISSUE TITLE
enum issue, default assignment of char 

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/cpp-textmate-grammar#278]
from https://github.com/microsoft/vscode-cpptools/issues/3867
```
enum
{
    a = '}'
};
```
@matter123 the end pattern of the enum is somehow beating out the char literal pattern. This issue doesn't exist for class/struct though.

**Comment by matter123** [comment]
On a related note. The single quote pattern can be made a non-range right? That would have prevented this bug from breaking more than the enum.

**Comment by jeff-hykin** [comment]
I'm pretty sure it can be. We'll have to cover all edge cases like \x000 syntax but I don't think theres any way for it to be split across a newline or have more than ~6 chars inside of it

**Comment by matter123** [comment]
So this happens because the pattern that follows the assignment is shy. This means it matches ` '` then the lookahead finds `}` and it's happy. capturing only a single `'` making the lookahead look for `}[^']` should help.

**Comment by matter123** [comment]
It looks like a single char can be split across a new line but I am not sure why you would do that as it does not embed the newline. https://godbolt.org/z/8SSgJc

**Comment by jeff-hykin** [comment]
*sigh* apparently chars can be multi character constants. 
```cpp
#include <iostream>
int main(int argc, char *argv[])
    {
        cout << 'for some reason\
        this compiles ' << "END\n";
        return 0;
    }
```

**Comment by matter123** [comment]
In particular, the character literal is promoted to an integer. I am not sure why yet.

**Comment by matter123** [comment]
[[lex.ccon]/2](http://eel.is/c++draft/lex.ccon#2) mentions "multicharacter literal".
> A multicharacter literal, or an ordinary character literal containing a single c-char not representable in the execution character set, is conditionally-supported, has type int, and has an implementation-defined value.

So it looks like it needs to stay a range.

**Comment by jeff-hykin** [comment]
pushed with v1.12.12
