### ISSUE TITLE
Deeply nested calls to operator[] break highlighting

### ISSUE THREAD

**Issue by ian-h-chamberlain** [jeff-hykin/cpp-textmate-grammar#279]
Opening at @matter123 's suggestion from https://github.com/microsoft/vscode/issues/76225#issuecomment-507754023

Minimal reproducible example in VSCode without any extensions. Possibly related to #37 ?
```cpp
#include <iostream>
#include <string>
#include <unordered_map>

using namespace std;

int
main()
{
    using DeeplyNestedMap = unordered_map<
        string,
        unordered_map<
            string,
            unordered_map<
                string,
                unordered_map<
                    string,
                    unordered_map<string, unordered_map<string, string>>>>>>;

    DeeplyNestedMap foo{{"a", {{"b", {{"c", {{"d", {{"e", {{"f", "g"}}}}}}}}}}}};

    cout << foo["a"]["b"]["c"]["d"]["e"]["f"] << endl;
    foo["long-key-here"]["another-long-key"]["even-more-long-keys"]["and-some-more"]
       ["really-long-keys"]["finally-the-last-one"] =
           foo["a"]["b"]["c"]["d"]["e"]["f"];

    cout << foo["long-key-here"]["another-long-key"]["even-more-long-keys"]
               ["and-some-more"]["really-long-keys"]["finally-the-last-one"]
         << endl;

    return 0;
}
```

![60522039-48bf7a80-9cb6-11e9-8b23-dc72a84a4782](https://user-images.githubusercontent.com/11131775/60533122-d4dc9c80-9ccc-11e9-9c97-ec404e636167.png)

With a comment to break it up, some of the highlighting is restored but not entirely:
![60522355-cc796700-9cb6-11e9-83ab-d7d827a47a7f](https://user-images.githubusercontent.com/11131775/60533143-e0c85e80-9ccc-11e9-90b9-f68e8bd1dd43.png)

Let me know if you need any more info, but I think that example should be enough to reproduce.

**Comment by jeff-hykin** [comment]
pushed with `v1.12.12`
