### ISSUE TITLE
Bad coloring of block comments in templates

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#283]
**From**: https://github.com/microsoft/vscode-cpptools/issues/3871
**By**: @HubertGruniaux

# Original Issue:

Issue Type: Bug
### To reproduce

Type this in a C++ soure file (e.g. main.cpp):

```c++
using type = another_type</* */>;
```

### Expected

The C-style block comment should be correctly highlighted.
### Actual

The comment is not correctly highlighted, instead `/* */` is considered as multiple C++ operators by the syntax highlighter.
### Screenshot
 
![image](https://user-images.githubusercontent.com/42495291/60593663-8a7a1f00-9da3-11e9-8ed0-4e5bc3cbb407.png)
### Other

Node, in GitHub, the code is correctly highlighted.

Also, set `C_Cpp.enhancedColorization` to `enabled` or `disabled` change nothing.

Extension version: 0.24.0-insiders3
VS Code version: Code - Insiders 1.36.0-insider (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T08:11:06.542Z)
OS version: Linux x64 5.0.0-20-generic snap

**Comment by jeff-hykin** [comment]
Fixed with `v1.12.14`
