### ISSUE TITLE
asterisks cause catostrophic backtracking

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#287]
Example:
```c++
// root scope
DEBUG_UART_PORT.print( F( "\r*********************** Program Info ***********************\r\n" ) );
```

The grammar fails to parse the line in a reasonable time.

Orginal Issue: microsoft/vscode/issues/76579
By: @git-tiger

**Comment by matter123** [comment]
So this is specifically because the comment contains `*`. This causes the `ref_deref` pattern to go into some form of catastrophic backtracking.

Possible solution:
- match strings earlier before any `ref_deref`
- limit the total amount of `*` that can be matched
- make `ref_deref` possessive. (why is it reluctant now?)

**Comment by matter123** [comment]
It looks like this may be present in any string that contains multiple asterisks, Not only when a function definition is expected.

**Comment by git-tiger** [comment]
I use multiple asterisks to separate code. 
Should I change all **** to another symbol? or wait for this to be resolved?

**Comment by matter123** [comment]
This is definitely a bug, I'll try to have a PR that fixes it sometime tomorrow.

**Comment by matter123** [comment]
The following example orginally from microsoft/vscode#76713 takes 97ms to parse.
(note the preceding spaces)
```c++
       "<!-- ********* MVB MESSAGES ********* -->\n"
```

The average time for meta.function.definition is 32ms. This suggests that function_definition is tried 3 different times on a one line file.

**Comment by matter123** [comment]
Some notes:
  - leading_space at the start of a function definition is not needed as qualifed_type starts with leading_space
  - qualified_types lookaheads in the beginning are expensive
  - the actual issues is the `MESSAGES *********` portion

**Comment by jeff-hykin** [comment]
this is really strange to me. I spent awhile optimizing the inline comment, specifically the `*`'s so that it could match it without any backtracking. Maybe there's something I'm not understanding that is actually causing it to be worse.

**Comment by matter123** [comment]
I don't think it's the online comment. regex 101's debugger suggests it's trying to match qualified type and the ref_deref

**Comment by matter123** [comment]
@jeff do you remember the rationale behind for why ref_deref can backtrack?

**Comment by jeff-hykin** [comment]
I don't and I'm actually debugging/rewriting it now cause its causing problems related to #282 as well

**Comment by matter123** [comment]
Not sure if its the best solution but if `function_definition` is anchored to the start of the line (or \G) then this issue is prevented.

**Comment by jeff-hykin** [comment]
Man this is strange to me, why would it have anything to do with *'s and anchoring?

**Comment by jeff-hykin** [comment]
removal of the lookaheads in ref/deref didn't seem to help

**Comment by jeff-hykin** [comment]
The issue also occurs for both these case in root
```
F( ***** Program Info ******** );
F( "***** Program Info ********" );
```

**Comment by matter123** [comment]
So what is happening is when parsing the line `       "<!-- ********* MVB MESSAGES ********* -->\n"` The looks for a function definition eventually starts at `MESSAGES`. At that point it thinks it has a valid type and starts looking for other parts, with ref_deref giving up `*`s as needed.

**Comment by matter123** [comment]
The bottom example doesn't have a performance issue because function_definition is not allowed in the parameter list

**Comment by jeff-hykin** [comment]
Why would 
```
F(
a ********
);
```
be different from
```
F(a ********);
```
?

**Comment by jeff-hykin** [comment]
Its also strange that function would have a problem when the operator overload syntax also looks for the qualified type and ref-deref

**Comment by matter123** [comment]
because function_definition is valid on that line. So it starts at `a` then looks for `ref_deref` on the first example, that line is never evaluated for a function definition.

**Comment by matter123** [comment]
but the operator overload starts with looking for the literal `operator` first.

**Comment by jeff-hykin** [comment]
it was updated to optionally look for the qualified type first (so that the return type would be highlighted)

**Comment by matter123** [comment]
The issue is that OnigScanner allows patterns to match anywhere in a string and it does not stop at the first match. That combination allows for function_definition to attempt to match in spots you wouldn't consider a function definition.

**Comment by jeff-hykin** [comment]
Hmm that is interesting, I didn't realize that's how it behaved.

**Comment by matter123** [comment]
Yeah, OnigScanner basically is just a collection of regex test patterns. It runs them all and then returns the first leftmost match. As a result, unanchored patterns have to test the entire line.

**Comment by jeff-hykin** [comment]
Fixed with `v1.12.15`, I went with your solution @matter123.
I created a `possible_begining_of_statement` variable that matches `/\G/.or(lookBehindFor(/;|\n/))`

**Comment by matter123** [comment]
shouldn't that be `(\G|^).or(lookBehindFor(/;|\n/))`?

**Comment by jeff-hykin** [comment]
Yeah and `;` should actually probably be left out because it will always be matched by `\G` because of the semicolon pattern

**Comment by matter123** [comment]
no afaik `\G` is only updated on begin/end patterns.

**Comment by jeff-hykin** [comment]
There were several edgecases: static, constexpr, inline templating, but I think I covered all of them and published with `v1.12.17`

**Comment by matter123** [comment]
technically still an issue. `char * string = "a string; buggy *******************";`

**Comment by jeff-hykin** [comment]
Is that a performance issue even with the new changes?

**Comment by jeff-hykin** [comment]
> no afaik `\G` is only updated on begin/end patterns.

(I forgot to reply) I didn't realize this. The pattern was updated to what you recommended

**Comment by matter123** [comment]
Yeah that is with v1.12.18. It is unavoidable unless you restrict function definitions to the start of a line.

**Comment by jeff-hykin** [comment]
Ah I see why now because of the semicolon. Without changing the textmate implementation the only fix I can think of is to turn every pattern into a range with a zero length end pattern and then use \G, but that would be an excessive amount of additional complexity so I don't plan on doing that for this one very unlikely edge case.

If performance continues to get worse as we add new patterns. And using ranges like that is actually successful. Then I might consider a tool for the library that abstracts away the complexity.

**Comment by matter123** [comment]
The operator_overload pattern needs the same treatment.
`"buggy *******************operator"` causes vscode to crash with v1.12.18.

It looks like Onigurma is smart enough to look for mandatory literals to anchor the pattern on. As a result only when the word operator is present does that behavior become visible.
