### ISSUE TITLE
if (t > 1) puts ("\n*******") causes freeze

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#291]
From @Jsoneft in https://github.com/microsoft/vscode/issues/76774

`if (t > 1) puts ("\n*******") `
Just keep adding `*` until it freezes.

**Comment by matter123** [comment]
Can you reproduce with 1.12.18? This looks like a duplicate of #287

**Comment by alexr00** [comment]
Nope, I just saw that :) Thank you!

**Comment by Jsoneft** [comment]
thanks !!!
