### ISSUE TITLE
#include scope is variable.other.macro.argument

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#292]
Code:
```
#include <iostream>
```

Scope of `include` used to be:
keyword.control.directive.include.cpp
meta.preprocessor.include.cpp
source.cpp

Scope of `include` now is:
variable.other.macro.argument.cpp
source.cpp

Scope of `iostream` used to be:
string.quoted.other.lt-gt.include.cpp
meta.preprocessor.include.cpp
source.cpp

Scope of `iostream` is now:
`source.cpp`

**Comment by jeff-hykin** [comment]
I'm unable to reproduce on `1.12.18` is there any other code with it?

![code](https://user-images.githubusercontent.com/17692058/60825506-70f52080-a171-11e9-8618-e378fd726704.png)

**Comment by matter123** [comment]
Regardless of whether it can be reproduced, macro argument doesn't belong outside of the macro context.

**Comment by alexr00** [comment]
I also can't reproduce with `1.12.18`. Thank you!
