### ISSUE TITLE
version in package.json is 1.0.0

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#293]
Grammars are pulled into VS Code using a script that pulls other useful info from the repo, such as the commit number and the version number. The version number is taken from the package.json. Until recently, the version number in the package.json was an easy way to tell if I had a fix already. Now, the version in package.json is always.1.0.0. Is there somewhere else I should be looking for the version? 

Having it in the package.json is very convenient because many other repos do the same.

**Comment by matter123** [comment]
As part of supporting other languages, each language has its own package.json. C++'s is at source/languages/cpp/package.json.

**Comment by alexr00** [comment]
I'll update our script then. Thank you!

**Comment by jeff-hykin** [comment]
Sorry about that, I didn't realize the package.json was being used outside of when the extension was published.
