### ISSUE TITLE
Issues with anonymous namespace

### ISSUE THREAD

**Issue by JayXon** [jeff-hykin/cpp-textmate-grammar#3]
Function parameters lost color
![image](https://user-images.githubusercontent.com/1552641/53233446-6bb69e00-36c8-11e9-9869-e4507cc7803f.png)

**Comment by JayXon** [comment]
Also `namespace` keyword was not highlighted, compared to named namespace:

![image](https://user-images.githubusercontent.com/1552641/53233998-905f4580-36c9-11e9-80fd-2d4cabae9a03.png)

**Comment by jeff-hykin** [comment]
Alright, this along with lots of other fixes are now pushed on v1.4.0 
Thanks for reporting it 👍

**Comment by JayXon** [comment]
Works now, thank you for the quick fix.
