### ISSUE TITLE
VSCode Better Perl Syntax - No string highlight on qq operator

### ISSUE THREAD

**Issue by donsequitur** [jeff-hykin/cpp-textmate-grammar#316]
Strings quoted with the qq operator are not highlighted properly.

![2019-07-18 09_07_35](https://user-images.githubusercontent.com/9997705/61459815-91746600-a93b-11e9-8ea3-878c7a60b39d.png)

https://perldoc.perl.org/perlop.html#Quote-and-Quote-like-Operators

**Comment by jeff-hykin** [comment]
Thanks for the documentation reference. I'm without a computer until the 23rd, but I'll work on it once I'm back. If there's other similar string-like operators I'll fix those as well.

**Comment by jeff-hykin** [comment]
I'm back and started working on this. Some of those patterns are going to be pretty difficult to include but I'll see what I can do.

**Comment by jeff-hykin** [comment]
Okay this should be fixed in `v1.0.9` and a separate issue with the ()'s {}'s and []'s was fixed as well. The ones that are a problem are multiline transliteration and substitution, but I'll track those on a separate issue
