### ISSUE TITLE
Support for trigraphs

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/cpp-textmate-grammar#32]
https://github.com/atom/language-c/issues/273
```
const char * a = "foo ??/" ??/??/";
```

**Comment by matter123** [comment]
Trigraphs were removed in C++17. Labeling this as C only

**Comment by matter123** [comment]
Digraphs are also unsupported.

<img width="195" alt="Screen Shot 2019-04-12 at 8 51 31 AM" src="https://user-images.githubusercontent.com/714007/56050265-41fd1900-5d00-11e9-9cfd-f1991a359d38.png">

The reasonable solution would be, to add to `tokens.rb` each special character
`#`, `\`, `^`, `[`, `]`, `|`, `{`, `}`, `~` and add their di/trigraph equivelent, and use these groups whenever looking for one of the special characters. This does pose an issue for lookbehinds, however.

**Comment by jeff-hykin** [comment]
Are digraphs also removed from the C++17 spec? 

Also wow that's incredible, I thought they never removed anything from spec no matter how bad/complicated it was 😆

**Comment by matter123** [comment]
No digraphs are still part of the c++ spec.

 The difference is that trigraphs are converted in phase1 of the translation. That means, unlike digraphs they don't have to be unique tokens. That causes other issues that digraphs don't so they were finally removed in c++17 after being deprecated in c++11.

**Comment by jeff-hykin** [comment]
closing in favor of #70
