### ISSUE TITLE
some interesting bug with ms-vscode.cpptools

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#323]
Missing highlight :
![image](https://user-images.githubusercontent.com/10380828/61629907-cfb1b280-acb8-11e9-96a2-8cd11afff561.png)
Missing highlight virtual:
![image](https://user-images.githubusercontent.com/10380828/61630035-320ab300-acb9-11e9-8850-5b3fd7abd07e.png)
wrong highlight with ms-cpptools enabled:
![image](https://user-images.githubusercontent.com/10380828/61630052-3d5dde80-acb9-11e9-9479-4e2305581d69.png)
maybe ms-cpptools update something.

**Comment by peaceshi** [comment]
https://github.com/weolar/miniblink49/releases

wke.h

**Comment by peaceshi** [comment]
![image](https://user-images.githubusercontent.com/10380828/61630886-7c8d2f00-acbb-11e9-8a12-a92ff708dab2.png)
utf8

**Comment by matter123** [comment]
These are likely duplicates of  https://github.com/microsoft/vscode-cpptools/issues/3933.

**Comment by matter123** [comment]
Closing as the provided scopes do not match the colors. If you can reproduce with cpptools "enhancedColorization" disabled, this can be reopened.
