### ISSUE TITLE
Double brackets are not highlighted if there is a full namespace reference c++

### ISSUE THREAD

**Issue by Yanpas** [jeff-hykin/cpp-textmate-grammar#336]
vscode 1.36.1
Example:
```cpp

int main() {
  ::puts("aa");
}
```
![image](https://user-images.githubusercontent.com/7345761/62146650-838cf080-b2fe-11e9-86bd-bd51225a73d0.png)

**Comment by matter123** [comment]
To clarify, the issue is that the `::` before `puts` is not marked as part of puts. Correct?

**Comment by Yanpas** [comment]
No, the issue it's that `"aa"` is not highlighted at all

**Comment by matter123** [comment]
I am unable to reproduce that issue. Please confirm that you have version 1.12.21 installed and enabled.

![Screenshot from 2019-07-31 00-49-49](https://user-images.githubusercontent.com/714007/62193783-5c99e300-b32d-11e9-812e-88e7f77128c9.png)

**Comment by Yanpas** [comment]
Cannot reproduce with code insiders too.
