### ISSUE TITLE
When testing .h files are treated with the C syntax

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#344]
This is most likely because `languageExtensionFor` does not handle duplicates correctly.

**Comment by matter123** [comment]
I think .h needs to be special cased as all of {obj,}c{,++} declare that they support .h. Neither first or last will pick c++

**Comment by jeff-hykin** [comment]
Why can't we just rename it to `.cpp`?

**Comment by matter123** [comment]
For integration tests, yes renaming would work. However when inspecting real code basis .h files exist, and it may be inconvenient, or one might forget to rename the file for this purpose.

There shouldn't be a difference how vscode and the testing framework handle the tokenization of files.

**Comment by jeff-hykin** [comment]
how does VS code figure out which syntax to use for `.h` files?

**Comment by matter123** [comment]
I think it just defaults to c++. `touch test.h: code test.h` shows it treats empty .h files as C++.

**Comment by matter123** [comment]
Well, the actual answer is much simpler. Only the C++ language contributes `.h`

https://github.com/microsoft/vscode/blob/master/extensions/objective-c/package.json

https://github.com/microsoft/vscode/blob/master/extensions/cpp/package.json

**Comment by jeff-hykin** [comment]
Haha, well I'm fine with taking `.h` off all the other languages
