### ISSUE TITLE
Consider making meta.conditional.preprocessor.cpp meta.preprocessor.conditional.cpp

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#349]
Snippet from VS Code tests:
```c++
#if B4G_DEBUG_CHECK
 fprintf(stderr,"num_candidate_ret=%d:", num_candidate);
 for(int i=0;i<num_candidate;++i)
 fprintf(stderr,"%d,",user_candidate[i]);
 fprintf(stderr,";");
#endif
```
Currently, our themes color `B4G_DEBUG_CHECK` using `meta.conditional`. With the latest grammar, this can no longer happen. If you swap `conditional` and `preprocessor` then the theme will continue to work as is.

**Comment by jeff-hykin** [comment]
Ah that scope name was a mistake, thanks for bringing it up. It was intended to be `meta.preprocessor.conditional`. I'll try to get that change out tonight

**Comment by jeff-hykin** [comment]
The change has been published, along with a few other minor tag-name restorations.
