### ISSUE TITLE
colorization broken after structured binding reference

### ISSUE THREAD

**Issue by bobbrow** [jeff-hykin/cpp-textmate-grammar#358]
In the following code example, the string literals do not get the correct colors.  If you remove the `&` the coloring will be correct.

```
#include <map>
using namespace std;
void func()
{
    map<int, std::string> m;
    for(auto& [id, name] : m)
        cout << id << ", " << name << endl;
    if(m.empty())
        cout << "empty map" << endl;
}
```

**Comment by matter123** [comment]
Is this with v1.13.2? I am unable to reproduce.

**Comment by bobbrow** [comment]
Ah, ok.  Then it seems this isn't in VS Code yet.  This was reported by a user of the C++ extension.  Sorry, I should have checked with Better Syntax before opening this issue.
