### ISSUE TITLE
Standards

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/cpp-textmate-grammar#369]
In terms of deciding what is/is not correct for the C++ syntax, this issue will be a continually updated listing of what definitions take priority.

Highest Priority: 
-  [The current C++ ISO standard](https://isocpp.org/std/the-standard)
-  [The current draft standard](http://eel.is/c++draft/)

For convenience, this site https://en.cppreference.com/w/ will be used as a standard for implementing the next-highest priority:
- The C++17
- The C++20 (draft)
- The C++14
- The C++11
- The C++03
- The C++98

Medium priority:
- [GNU Pre-defined macros](https://gcc.gnu.org/onlinedocs/cpp/Predefined-Macros.html) 
- [Microsofts Visual Studio C++]( https://docs.microsoft.com/en-us/cpp/cpp/cpp-language-reference?view=vs-2019) 

Low priority:
- [Doxygen](http://www.doxygen.nl/manual/docblocks.html)

**Comment by soroshsabz** [comment]
@jeff-hykin C++20 is not draft at now, so I think this issue must be update
