### ISSUE TITLE
syntax highlighting breaks after [ ] [ ]

### ISSUE THREAD

**Issue by sykoram** [jeff-hykin/cpp-textmate-grammar#37]
![image](https://user-images.githubusercontent.com/41990490/54617484-a3173100-4a61-11e9-855d-9494dfb10363.png)
syntax highlighting breaks after [ ] [ ]
it works only in ( )
it works again after first {

**Comment by jeff-hykin** [comment]
Thanks for the details, that was exactly what we needed to know to fix it.
Thanks @matter123 for getting a fix in. I had to modify it a bit as it didn't play nice with the other code, but you corrected the source of the problem.

I went ahead an posted a fix just now with version 1.6.5.
