### ISSUE TITLE
"typename" keyword not highlighted at the beginning of a trailing-return-type

### ISSUE THREAD

**Issue by HighCommander4** [jeff-hykin/cpp-textmate-grammar#371]
When a return type is written in trailing position, and begins with `typename`, the `typename` keyword is not highlighted.

Example:

```
template <typename T>
auto foo() -> typename T::type;  // <--
```

**Comment by jeff-hykin** [comment]
Thanks for reporting this, I was unaware that the trailing return type was allowed on regular functions. We're going to need to create new patterns for this

**Comment by HighCommander4** [comment]
I don't really understand how TextMate grammars work, but I am kind of curious as to why this and #370 require special handling. `template` are `typename` are not context-sensitive keywords -- _every_ occurrence of those tokens is a keyword.

**Comment by matter123** [comment]
While it is true that typename and template are not context-sensitive keywords, We don't have a pattern to just tag them as often those keywords help determine what subsequent and previous tokens are.

For example, we have a pattern that says basically, "there is a qualified-type following 'typename'". If typename was just consumed it would make it more difficult to match that pattern. That pattern also cant be context-free as `template<typename, typename>` is a completely valid set of template parameters.

Luckily this should hopefully be simple enough by specifying that following `->` when in the head of a function definition is "maybe typename, then qualified-type"

**Comment by matter123** [comment]
Trailing return-type, additionally supports `decltype` expressions.

Examples:
 - `decltype(auto)` - both decltype and auto are keywords (this should be the only type allowed an a decltype expression
 - `decltype(A)` - `A` is a variable, or at least a non type, and is probably a parameter
 - anything else inside decltype is an expression.

**Comment by jeff-hykin** [comment]
> I don't really understand how TextMate grammars work
@HighCommander4 

Theres only two tools
1. match less-than-1-line with regex (e.g. `typename`), and attach names to the regex capture groups
2. match less-than-1-line with regex (e.g. `sizeof(`), which triggers a new context (changes what patterns are allowed), then (eventually) match a different less-than-1-line regex (e.g. `)`) to stop and go back to the old context

Thats basically it, so we have to get really really creative with those things to match stuff like functions that have lots of their pieces on separate lines.

Those keywords might not be context sensitive, but TextMate definitely is

**Comment by matter123** [comment]
Closing in favor of #405
