### ISSUE TITLE
Issue with RefPtr

### ISSUE THREAD

**Issue by JayXon** [jeff-hykin/cpp-textmate-grammar#385]
![image](https://user-images.githubusercontent.com/1552641/64387241-38968500-cff0-11e9-84e3-d46acecf2cdd.png)

Code can be found at https://fuchsia.googlesource.com/fuchsia/+/master/zircon/system/core/bootsvc/main.cc#267

**Comment by matter123** [comment]
Can you reproduce with the setting `"C_Cpp.enhancedColorization": "Disabled",`?

**Comment by JayXon** [comment]
nope
![image](https://user-images.githubusercontent.com/1552641/64389328-16543580-cff7-11e9-9add-a5dd7bb63743.png)

**Comment by matter123** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-cpptools/issues/3933

**Comment by JayXon** [comment]
But I was not typing and it stays like that forever?

**Comment by matter123** [comment]
Maybe consider filing a separate issue with vscode-cpptools then. If disabling enhancedColorization fixies the issue then the issue lies with vscode-cpptools.

**Comment by JayXon** [comment]
Looks like microsoft/vscode-cpptools#3901
