### ISSUE TITLE
"invalid.unknown.documentation.command.cpp" scope occurs after /** \comment */

### ISSUE THREAD

**Issue by sean-mcmanus** [jeff-hykin/cpp-textmate-grammar#393]
Use any comment starting with `/**` that also has a `\` and some text after it, e.g.

`/** \comment comment */`

That's an artificial example, but another example occurs in our real world source code (which doesn't use doxygen style comments).

It causes the comments to be rendered as "invalid.unknown.documentation.command.cpp" (e.g. red instead of green).

It doesn't repro with VS Code 1.38.1 without the Better C++ Syntax extension, so it may be a regression from the recent change to support doxygen comments.

**Comment by jeff-hykin** [comment]
`v1.14.7` pushed just now, and it removes the `invalid.unknown.documentation`. Let us know if similar problems persist
