### ISSUE TITLE
C++ highlighting is broken for comments in the template arguments

### ISSUE THREAD

**Issue by hokein** [jeff-hykin/cpp-textmate-grammar#394]
Testcase:

```cpp
template <>
struct /* entity.name.type.class.cpp */ Tmpl2<
    /* storage.type.primitive.cpp */ int,
    /* storage.type.primitive.cpp */ bool>;
```

Screenshot in VSCode 1.38.1:

![image](https://user-images.githubusercontent.com/2557445/66051381-27795f00-e52f-11e9-90ed-1ab703e49bfa.png)

**Comment by matter123** [comment]
This has already been fixed. please update to vscode insiders or the current extension version.
