### ISSUE TITLE
Highlighting broken for most function signatures in C++

### ISSUE THREAD

**Issue by rianquinn** [jeff-hykin/cpp-textmate-grammar#398]
Checklist

- [X] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [X] This bug exists for C
- [X] This bug exists for C++
- This bug exists for Objective-C
- This bug exists for Objective-C++

## The code with a problem is:
```
static inline const std::string &foo()
{ }

static const std::string &foo()
{ }

constexpr const std::string &foo()
{ }

static constexpr const std::string &foo()
{ }

constexpr static const std::string &foo()
{ }

constexpr static void foo()
{ }

static constexpr void foo()
{ }

constexpr void foo()
{ }

static void foo()
{ }
```

## It looks like:
![image](https://user-images.githubusercontent.com/5932003/66771369-96e53c00-eea9-11e9-9de8-afb113e3cc5e.png)

## It should look like:
The white text should be purple. It is almost as if this is counting the total number of decorators and stopping at 2.

**Comment by jeff-hykin** [comment]
@matter123 Hmm the following pattern should cover this, but obviously its not. Something more complicated is at play.
```
zeroOrMoreOf(
                Pattern.new(
                    match: variableBounds[@cpp_tokens.that(:isFunctionSpecifier).or(@cpp_tokens.that(:isStorageSpecifier))],
                    tag_as: "storage.modifier.$match"
                ).then(std_space)
            )
```

The words in white are all still inside function head

**Comment by matter123** [comment]
@jeff-hykin This is an issue that crops up repeatedly, capturing inside of a quantifier likely does not do what you want.

The correct pattern should be

```ruby
Pattern.new(
  match: zeroOrMoreOr(variableBounds[@cpp_tokens.that(:isFunctionSpecifier).or(@cpp_tokens.that(:isStorageSpecifier))])
  includes: [
    Patteren.new(
      match: variableBounds[@cpp_tokens.that(:isFunctionSpecifier).or(@cpp_tokens.that(:isStorageSpecifier))],
      tag_as: "storage.modifier.$match",
    ),
  ],
```

One of the roadmap items to a gem is a transformation that fixes this. Doing it generically is just suprisingly complicated.

**Comment by rianquinn** [comment]
Is there a way for me to apply the above fix to test this on my end?

**Comment by jeff-hykin** [comment]
> @jeff-hykin This is an issue that crops up repeatedly, capturing inside of a quantifier likely does not do what you want.

Wow I feel really dumb, I should know better by now. It'll be nice once there is a warning.

**Comment by jeff-hykin** [comment]
> Is there a way for me to apply the above fix to test this on my end?

Yup, install the `v1.14.10` version of the extension which was published just now. Let me know if you run into any other issues

**Comment by rianquinn** [comment]
Yup, it appears to be addressed. Out of curiosity, I had to install the Better C++ Syntax extension, but my issue is with native VSCode and the C++ Extension by Microsoft. Are these two tied at the hip or am I missing something (i.e., Microsoft sent me to this project, but it seems like they have the same bug... should I report it to them again?)

**Comment by matter123** [comment]
No, vscode will receive the fix the next time they update the grammar files.

**Comment by jeff-hykin** [comment]
@rianquinn just to clarify, theres the VS Code team, and they regularly copy down this repo and pull it into VS Code after it is shown to be stable. Then a separate team works on the C++ extension, which is a smart tool that parses the code and adds small color adjustments here and there on top of the colors/syntax that are assigned by this repo.

Downloading this extension just gives you the latest version of the basic native VSCode C++  syntax highlighting.

**Comment by rianquinn** [comment]
perfect... thanks a ton for clarifying
