### ISSUE TITLE
Editing results in incorrect syntax highlighting

### ISSUE THREAD

**Issue by DaanDeMeyer** [jeff-hykin/cpp-textmate-grammar#402]
When editing C code, I get incorrect syntax highlighting, refreshing the Visual Studio Code window fixes the highlighting.

When editing:

![image](https://user-images.githubusercontent.com/9395011/67161489-49f6df00-f35b-11e9-82e8-60f581bcb6a2.png)

After reloading:

![image](https://user-images.githubusercontent.com/9395011/67161493-5d09af00-f35b-11e9-9f05-298dfa588de6.png)

**Comment by matter123** [comment]
Please confirm that this reproduces with the C/C++'s enhanced colorization disabled.

**Comment by jeff-hykin** [comment]
@DaanDeMeyer , if you could fill out the new-issue bug report completely it would be a lot easier to address the issue. I'll reopen the issue once its filled out.
![Screen Shot 2019-10-20 at 10 16 04 AM](https://user-images.githubusercontent.com/17692058/67161721-c6b99700-f322-11e9-89c0-69b4b1afeb5d.png)

**Comment by DaanDeMeyer** [comment]
Checklist

- [X] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

I'm not using the C/C++ extension.

- [X] This bug exists for C
- [X] This bug exists for C++
- [?] This bug exists for Objective-C
- [?] This bug exists for Objective-C++

## The code with a problem is:

No specific piece of code it appears everywhere in [reproc](https://github.com/DaanDeMeyer/reproc).

## It looks like:

C++ screenshot:

![image](https://user-images.githubusercontent.com/9395011/67161776-1ff2ec00-f35e-11e9-81b2-1e8a6dae56d8.png)

## It should look like:

After reloading:

![image](https://user-images.githubusercontent.com/9395011/67161782-313bf880-f35e-11e9-9b49-45ddd47918da.png)

Notice the brace that's highlighted differently.

**Comment by jeff-hykin** [comment]
Are you using a different extension to get the red underline? I'm unable to reproduce the error. The TextMate grammar (this repo) shouldn't be capable of changing like that before/after a reload, but that type of behavior is very common for language-server extensions.

**Comment by DaanDeMeyer** [comment]
I'm using clangd. Do you think that it could be doing something in that regard?

**Comment by DaanDeMeyer** [comment]
Turns out clangd's semantic highlighting was causing the issue.
