### ISSUE TITLE
Macro highlighting issue

### ISSUE THREAD

**Issue by rianquinn** [jeff-hykin/cpp-textmate-grammar#406]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [x] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```
#if defined(BAREFLANK_THROW_ON_CONTRACT_VIOLATION)

#define BAREFLANK_CONTRACT_CHECK(test, file, line)                             \
    if (BAREFLANK_UNLIKELY(!test)) {                                           \
        throw bfn::exception("contract violation at [" line "]: " file);       \
    }

#elif defined(BAREFLANK_TERMINATE_ON_CONTRACT_VIOLATION)

#define BAREFLANK_CONTRACT_CHECK(test, file, line)                             \
    if (BAREFLANK_UNLIKELY(!test)) {                                           \
        std::cerr << "contract failure at [" line "]: " file << '\n';          \
        std::terminate();                                                      \
    }

#elif defined(BAREFLANK_CUSTOM_ON_CONTRACT_VIOLATION)

#else

#define BAREFLANK_CONTRACT_CHECK(test, file, line)

#endif
```

## It looks like:
![image](https://user-images.githubusercontent.com/5932003/67202293-cb03b400-f3f7-11e9-8520-28266200427e.png)

## It should look like:
The macro in the "if" is not colored the same as the macro in the "elseif". If I swap them, the color doesn't follow the swap (meaning its not because one is defined and the other is not, its the highlighter treating them differently).

**Comment by matter123** [comment]
This is caused by the C/C++ extension. In particular the option "dim inactive regions".
