### ISSUE TITLE
Bitwise left shift operator overload

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/cpp-textmate-grammar#410]
From: https://github.com/microsoft/vscode-cpptools/issues/4512

**Comment by matter123** [comment]
Likely an ordering issue `<` is before `<<=` but `>>=` is before `>`

**Comment by jeff-hykin** [comment]
yup it was, I just pushed a fix for it with `v1.14.11`.

There could be other ordering issues though, I didn't do a exhaustive check.
This could also happen in other places that are using `@tokens`

**Comment by matter123** [comment]
More generally, `tokensThat` should order its results such that no items representation, earlier in the array is a subset of the current items representation.

**Comment by jeff-hykin** [comment]
Yeah, and that should be possible since they're all simple strings
