### ISSUE TITLE
perl: <=> ligature broken in vscode

### ISSUE THREAD

**Issue by clscott** [jeff-hykin/cpp-textmate-grammar#413]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [ ] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```
1 <=> 2
a <=> a    
} <=> {
) <=> }
: <=> :
| <=> |
! <=> !
#1 <=> 2
#a <=> a    
#} <=> {
#) <=> }
#: <=> :
#| <=> |
#! <=> !

#for my $kw (sort {$candidate_kws{$b}->{weight} <=> $candidate_kws{$a}->{weight} } keys %candidate_kws){}

for my $kw (sort { $candidate_kws{$b}->{weight} <=> $candidate_kws{$a}->{weight} } keys %candidate_kws){}
```

## It looks like:
 * Using Dark+ theme
 * Using Fira Code font for ligatures (basic config)
 * Only disabling the Better Perl Syntax extension works to enable the ```<=>``` rendering
```
"editor.fontFamily": "Fira Code",
"editor.fontLigatures": true,
```

![broken-spaceship-in-sort](https://user-images.githubusercontent.com/18856/68498779-b9a70e00-0225-11ea-8c48-eddfafbcc7f8.png)
![list-of-broken-spaceships](https://user-images.githubusercontent.com/18856/68498791-be6bc200-0225-11ea-8944-eb92333c1efc.png)

## It should look like:
 
![fixed-spaceship](https://user-images.githubusercontent.com/18856/68499576-7ea5da00-0227-11ea-886f-ca90b1bbdeba.png)

**Comment by jeff-hykin** [comment]
Hey @clscott thanks for reporting this. I went ahead and moved this issue to perl repo [here](https://github.com/jeff-hykin/better-perl-syntax/issues/1)
