### ISSUE TITLE
"enum" getting tokenized as an enum even when it's part of another word

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#414]
From @peaceshi in https://github.com/microsoft/vscode/issues/84410

Sample is at https://github.com/kcat/openal-soft/blob/74cbba511d6b71634d07d44a822c826400fe967d/al/error.cpp#L95

![20191110173447](https://user-images.githubusercontent.com/10380828/68541915-7218b180-03e0-11ea-953a-a6a0566fe2f9.png)

**Comment by jeff-hykin** [comment]
Fix pushed with `v1.14.13` 👍

**Comment by alexr00** [comment]
Thanks for the very quick fix! I've pulled in `v1.14.13` to VS Code.
