### ISSUE TITLE
Highlight In and Out parameters in Doxygen comments

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#418]
![image](https://user-images.githubusercontent.com/56022622/69000279-d207de80-0931-11ea-9a4e-1ed872717849.png)

Ref: http://www.doxygen.nl/manual/commands.html#cmdparam

**Comment by matter123** [comment]
@gb-esat, I am not quite sure what scopes to assign to in and out do you have any preferences?

Here are some scopes that I thought of in Dark+

`keyword.other.parameter.direction.$match`,
`storage.modifier.parameter.direction.$match`:
![Screen Shot 2019-11-16 at 15 52 04](https://user-images.githubusercontent.com/714007/69000728-21460480-0889-11ea-9fb3-d8cd222c0e75.png)

`variable.other.$match`:
![Screen Shot 2019-11-16 at 15 54 25](https://user-images.githubusercontent.com/714007/69000750-6b2eea80-0889-11ea-8c9b-6a71a6ba89a2.png)

`markup.other.$match`:
![Screen Shot 2019-11-16 at 15 58 34](https://user-images.githubusercontent.com/714007/69000787-f7d9a880-0889-11ea-9600-6e9c51212ac9.png)

Other themes may provide different coloring for different scopes.

**Comment by gb-esat** [comment]
The first one looks good to me.

**Comment by gb-esat** [comment]
Thanks @matter123 !

**Comment by Gorgeous2017** [comment]
@matter123 
hey, I noticed that this feature could work in v1.43.0. But today I update to v1.43.1, it counldn't work.....What wrong with it??

**Comment by matter123** [comment]
1.43.1 is a recovery release, where the vscode team fixes any major bugs in the .0 release. In this instance #460 was a major issue and the grammar had to be reverted to the one in 1.42. see https://github.com/microsoft/vscode/commit/dc90cfbc579c373e07cae55f4a946ed522e5c1b5

**Comment by Gorgeous2017** [comment]
> 1.43.1 is a recovery release, where the vscode team fixes any major bugs in the .0 release. In this instance #460 was a major issue and the grammar had to be reverted to the one in 1.42. see [microsoft/vscode@dc90cfb](https://github.com/microsoft/vscode/commit/dc90cfbc579c373e07cae55f4a946ed522e5c1b5)

I got it. So in which version of  vscode can I use the 1.43 grammar?

**Comment by matter123** [comment]
You can install the better c++ syntax extension on any version, use vscode insiders, (tomorrow), or stay on 1.43.0
