### ISSUE TITLE
new and delete not colorized

### ISSUE THREAD

**Issue by ember91** [jeff-hykin/cpp-textmate-grammar#42]
**Describe the bug**
- OS and Version: Ubuntu 18.04.2 LTS
- VS Code Version: 1.32.3
- Better C++ Syntax Extension Version: 1.6.5
- Other extensions you installed (and if the issue persists after disabling them): C/C++. The issue persists after disabling it.
- A clear and concise description of what the bug is: The keywords 'new' and 'delete' are not colorized at all.

**To Reproduce**
1. Create a new file with extension '.cpp'.
2. Input the code below in the newly created file. 
```
int main()
{
    int* i = new int;
    delete i;
}
```

**Expected behavior**
'new' and 'delete' should be colorized.

**Additional context**
May be true for other keywords as well.

**Comment by matter123** [comment]
This is an issue with your color theme.

`new` correctly has the textmate scope of `keyword.operator.memory.new` and `delete`
correctly has the scope of `keyword.operator.memory.delete`.

You can fix this by adding the following snippet to settings.json.
```
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"name": "memory operatots.memory",
				"scope": ["source.cpp keyword.operator"],
				"settings": {
					"foreground": "#bc7ed7", // color you want it to be
					"fontStyle": "" // bold/underline/italics or none
				}
			}
		]
	},
```

You may want to file an issue with your theme as this grammar will soon be the default grammar for C/C++

Further discussion relating to theme colors should be directed at #7.

**Comment by ember91** [comment]
This is correct. For reference, of the default themes Light (Visual Studio), Light+ (default light), Dark (Visual Studio), Dark+ (default dark), and High Contrast all have this problem with new and delete being just white or dark. Sorry for the misreport.
