### ISSUE TITLE
$reference in generated grammar

### ISSUE THREAD

**Issue by lieene** [jeff-hykin/cpp-textmate-grammar#424]
Checklist

- [ ] This bug exists for C++

## The code with a problem is:

https://github.com/jeff-hykin/cpp-textmate-grammar/blob/a0f03bfce2c9eed3fbe33429b00f174a9775c3b6/syntaxes/cpp.tmLanguage.json#L3066

_$reference(directive)_ not replaced by group id

**Comment by matter123** [comment]
Duplicate of #355. I did not realize that at the time, thank you for reporting however.
