### ISSUE TITLE
if constexpr causes incorrect syntax highlighting for rest of line

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#43]
Example code
```
int main() {
      if constexpr(std::is_signed_v<char>>) { // no syntax highlighting
      }
}
```
The entirety of `constexpr(std::is_signed_v<char>>) { // no syntax highlighting` has the scope of `meta.function-call`.

Additionally, the developer tools console has the error `[2] - Grammar is in an endless loop - Grammar pushed the same rule without advancing`.

Neither the `begin` or `end` of the range pattern for `"c_function_call"` consume any characters. Per https://github.com/Microsoft/vscode-textmate/issues/12 VSCode has limited support for zero width range matches.

**Comment by jeff-hykin** [comment]
Currently I'm traveling, but as soon as I get back (next week) I'll go over the merge and push an update.

**Comment by jeff-hykin** [comment]
<img width="585" alt="Screen Shot 2019-03-31 at 12 59 50 AM" src="https://user-images.githubusercontent.com/17692058/55285366-503a5500-5350-11e9-836c-d33c3ae2125f.png">
Looks good.

Thats interesting about the endless loop, I've actually never looked at the developer console for the grammar 😅 I should probably start using that.
