### ISSUE TITLE
C++ asm statement not recognized

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#433]
From @RSDuck in https://github.com/microsoft/vscode/issues/87991

Checklist

- [x] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```c++
void test()
{
  asm
  (
    : : :
  );
}
```

## It looks like:
See that `asm` doesn't have the right scope.

![image](https://user-images.githubusercontent.com/38270282/71812917-a7581d80-3078-11ea-8e02-29b37b66121d.png)

## It should look like:
Move the opening paren after `asm` to the same line and it gets the right scope.
![image](https://user-images.githubusercontent.com/38270282/71812988-cb1b6380-3078-11ea-9e2d-265d8a50fe48.png)

**Comment by jeff-hykin** [comment]
`v1.14.17` published with the fix thanks to @matter123
