### ISSUE TITLE
Character template with opening bracket makes rest of file highlighted as text

### ISSUE THREAD

**Issue by MinusGix** [jeff-hykin/cpp-textmate-grammar#438]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [?] This bug exists for Objective-C++

## The code with a problem is:
```
template<char C>
struct Example {};
struct Alpha : public Example<'{'> {};
struct Beta {};
int main () {
    int x = 52;
}
```

## It looks like:
![2020-01-12-201241_264x113_scrot](https://user-images.githubusercontent.com/13157904/72229962-f66de900-3577-11ea-81eb-75fb23ab0a3b.png)
Theme: Noctus Obscurio. Also happens for a variety of other themes.
## It should look like:
Should stop highlighting it as if it is a long multi-line character sequence.  
  
This problem also occurs if I run VScode without extensions enabled.  
Note: There is also a smaller issue with using the character `<` as a char template parameter, but it only makes the `Example` text highlighted slightly oddly, not nearly as notable as the above problem, though.

**Comment by jeff-hykin** [comment]
Should be fixed now, thankfully it was just a matter of just deleting a pattern. Let me know if the problem persists
