### ISSUE TITLE
The extension does not work in remote-ssh environment

### ISSUE THREAD

**Issue by xspeed1989** [jeff-hykin/cpp-textmate-grammar#440]
The VSC Version:1.41.1
remote-ssh：
![image](https://user-images.githubusercontent.com/5162926/72673711-67962a80-3aa9-11ea-98c3-2237e41e38b0.png)

**Comment by matter123** [comment]
The Better C++ Syntax extension does not highlight typedefs inside classes. If you see that highlighting when editing files locally, you have an extension that provides semantic highlighting for C++, most likely the C/C++ extension.

You will need to file an issue with your extension that provides semantic highlighting.
