### ISSUE TITLE
throws doxygen command not highlighted

### ISSUE THREAD

**Issue by alexFickle** [jeff-hykin/cpp-textmate-grammar#444]
Checklist

-  This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
-  This bug exists for C++

## The code with a problem is:
```.cpp
/// @throws std::runtime_error On error.
void test();
```

## It looks like:
![current](https://user-images.githubusercontent.com/20073418/73419957-9f417580-42e6-11ea-9e25-a1657692d5df.png)

## It should look like:
Pretend that throw is throws.

![desired](https://user-images.githubusercontent.com/20073418/73419994-c304bb80-42e6-11ea-8833-901acbc9fca1.png)

Hopefully just adding throws to an array would work: https://github.com/jeff-hykin/cpp-textmate-grammar/blob/85b9008b406cc9d3b1c9e779e94cc071116c8426/source/shared_patterns/doxygen.rb#L196

**Comment by jeff-hykin** [comment]
published with `v1.14.23`
