### ISSUE TITLE
variables not being tokenized

### ISSUE THREAD

**Issue by tat3r** [jeff-hykin/cpp-textmate-grammar#45]
Variables are not being tokenized in global or local scope.  This is an issue with C syntax but possibly exists in C++ as well.

<img width="54" alt="Screen Shot 2019-03-27 at 10 32 44 PM" src="https://user-images.githubusercontent.com/449059/55128508-d13fe500-50e1-11e9-9684-6973eb170311.png">

<img width="175" alt="Screen Shot 2019-03-27 at 10 33 04 PM" src="https://user-images.githubusercontent.com/449059/55128510-d4d36c00-50e1-11e9-87ec-8f950f70310c.png">

**Comment by jeff-hykin** [comment]
Sadly I think this is similar to #39. 

Textmate markup isn't smart enough to know when a name is a variable.

It could be possible to tag it on declarations though, but it would only work for primitives. Is the issue for the declaration or for all instances of variables?

**Comment by tat3r** [comment]
all instances, however with foo.bar or foo->bar, bar gets picked up, but foo is still missing.

**Comment by jeff-hykin** [comment]
<img width="346" alt="Screen Shot 2019-03-28 at 7 06 55 PM" src="https://user-images.githubusercontent.com/17692058/55200563-afe80300-518c-11e9-85f6-e8a978d4608b.png">
`foo.bar` should be picked up.

Sadly, tagging all instances is impossible without a powerful C/C++ specific. Its way outside the ability of TextMate grammars.

For example:
```
#ifdef thing
    int x = 10;
#else 
    class x { };
#endif 
```
Its basically impossible to know what x is without emulating the entire C/C++ preprocessor

**Comment by matter123** [comment]
`struct f foo` Could mark `f` as type like C++ does.
additionally for both C and C++  `enum f foo` should mark `f` as a type.

C++ | C
----|-----
![Screenshot from 2019-03-28 18-30-55](https://user-images.githubusercontent.com/714007/55203206-ecfdc680-5187-11e9-93c3-cc4a3048669f.png) | ![Screenshot from 2019-03-28 18-32-32](https://user-images.githubusercontent.com/714007/55203214-f0914d80-5187-11e9-8700-44556cbdcfe4.png)

**Comment by jeff-hykin** [comment]
Lets create a new issue for that.
