### ISSUE TITLE
Is there a way to get VSCode to tell you the scope(s) assigned to the token under the cursor?

### ISSUE THREAD

**Issue by HighCommander4** [jeff-hykin/cpp-textmate-grammar#455]
This is a question rather than a bug report; apologies if this is the wrong place to ask it.

Sometimes, it's not immediately obvious whether an unexpected color for a token is a problem with the syntax highlighting extension assigning the wrong scope(s) to a token, or with the theme assigning the wrong color(s) to a scope.

To debug this, it would be helpful if there was some debugging tool / mode where you could hover over a token (or activate a command with a token selected, etc.) and get VSCode to tell you what scope(s) are assigned to that token. Is there a way to do this?

**Comment by matter123** [comment]
Command Palate: >Developer: Inspect Editor Tokens and Scopes

**Comment by HighCommander4** [comment]
Thanks, exactly what I was looking for :)
