### ISSUE TITLE
Types in C are missing highlighting

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#46]
From #45 
Effects: C

The code fragment `struct f foo` has incorrect highlighting. `f` has the scope `source.c` when it should have `entity.name.type.c source.c`

Image:
![C](https://user-images.githubusercontent.com/714007/55203214-f0914d80-5187-11e9-8700-44556cbdcfe4.png)
Example:
```C
struct f foo;
int func() {
    struct f foo;
}
```

**Comment by matter123** [comment]
all three types used in various ways

```C
/* Forward Declaration */
struct A b;
enum B c;
union C d;

/* Function Declaration */
void a(struct A b);
void b(enum B c);
void c(union C d);
void d(A b);

/* Definition */
struct A {
	enum B c;
	union C d;
};
enum B {
	struct A d;
	union C d;
};
union C {
	struct A b;
	enum B c;
};
```
as of 1.8.7:
 * none of the typenames have highlighting
 * probably_a_parameter corrently marks the parameter names

**Comment by jeff-hykin** [comment]
I'm going to merge this into #70 until the C syntax gets on the todo list
