### ISSUE TITLE
First six characters of function names are a different color when coroutine keywords used.

### ISSUE THREAD

**Issue by epezent** [jeff-hykin/cpp-textmate-grammar#464]
As the title states, the first 6 characters of function names containing coroutine keywords is incorrectly colored. This issue does not exist with `"C_Cpp.enhancedColorization": "Disabled"`. It is likely related to:

https://github.com/jeff-hykin/cpp-textmate-grammar/issues/12

## Checklist

- [**NO** ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [**NO** ] This bug exists for C
- [**YES** ] This bug exists for C++
- [**NO** ] This bug exists for Objective-C
- [ **MAYBE**] This bug exists for Objective-C++

## The code with a problem is:
```
/// simplest example
Enumerator coroutine() {
    co_yield nullptr;
}
```
## It looks like:

**Theme:** Noctis Uva
![image](https://user-images.githubusercontent.com/29577475/77824860-a660e600-70d3-11ea-9283-27ab8bdd54b3.png)

**Theme:** Dark+ (default)
![image](https://user-images.githubusercontent.com/29577475/77824877-c42e4b00-70d3-11ea-9a4e-a2437cf900f9.png)

## It should look like:
The function name `coroutine` should be one color (e.g. green/yellow).

**Comment by matter123** [comment]
As this issue only exists when enhancedColorization is enabled, you need to file this issue with https://github.com/microsoft/vscode-cpptools.
