### ISSUE TITLE
enum types missing highlighting

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#47]
From: #45
Effects: C, C++

In the declaration `enum bar b;`, `bar` has incorrect highlighting. `bar` has the scope of `source.{c,cpp}`, it should have the scope `entity.name.type.{c,cpp} source.{c,cpp}`

Image:
![C++](https://user-images.githubusercontent.com/714007/55203206-ecfdc680-5187-11e9-93c3-cc4a3048669f.png)

Example:
```C++
enum bar b;
int foo() {
    enum bar b;
}
```

**Comment by matter123** [comment]
The named reference capture on https://github.com/jeff-hykin/cpp-textmate-grammar/blob/37625cff52332dd0a079709f2ac79507c89d7b23/generate.rb#L1337 results in a grammar that uses the whole line capture `entity.name.type.$0.cpp`. Am I using `$reference()` incorrectly?

**Comment by matter123** [comment]
This should remain open until the same fix is applied for the C grammar.

**Comment by jeff-hykin** [comment]
@matter123 Sorry I just saw your question on here. Thanks for taking a look into the reference issue already.

**Comment by matter123** [comment]
Closing in favor of #46.
