### ISSUE TITLE
Syntax highlighting of parameters, user-defined classes and STL classes (e.g. std::string) does not work properly in WSL

### ISSUE THREAD

**Issue by alisherzhaken** [jeff-hykin/cpp-textmate-grammar#473]
Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [ ] This bug exists for C++

## The code with a problem is:
```
#include <iostream>

struct Person {
    std::string name;
    Person() = default;
    Person(const char* name) :
        name{name} 
        {}
    ~Person() = default;
};


int main() {
    Person p {"John"};
    std::string str {"Hello"};
    std::cout << p.name << '\n';
    std::cout << str << '\n'; 
}
```

## It looks like:
WSL: 
![Untitled (2)](https://user-images.githubusercontent.com/43493539/81450826-1787c480-917b-11ea-8350-475db956ec18.png)

## It should look like:
Windows:
![Untitled (3)](https://user-images.githubusercontent.com/43493539/81451018-7cdbb580-917b-11ea-9afd-cde2bde76955.png)

**Comment by matter123** [comment]
Hi, this is an issue with the C/C++ Extension's Enhanced Colorization. Please file this issue at https://github.com/microsoft/vscode-cpptools
