### ISSUE TITLE
What is the color scheme used in the screenshot in the readme?

### ISSUE THREAD

**Issue by benj02** [jeff-hykin/cpp-textmate-grammar#475]
This is not a bug, I just want to know which color theme was used in the screenshots shown in the readme. It looks really nice but I can't seem to find it on the VSCode marketplace.

Before                     | After
:-------------------------:|:-------------------------:
![material_before](https://user-images.githubusercontent.com/17692058/59826753-83abd080-92fc-11e9-9dfb-d891da55cd13.png) |![material_after](https://user-images.githubusercontent.com/17692058/59826766-8ad2de80-92fc-11e9-9bd6-3496ed5c917b.png)

@jeff-hykin thank you! :)

**Comment by jeff-hykin** [comment]
At the time it was the Material Theme, although the exact look might have changed some by now.
