### ISSUE TITLE
generate_c.rb does not generate grammar

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#48]
`generate_c.rb` is not able to generate `syntaxes/c.tmLanguage.json` as It appears to be a stub and `c_grammar` is not a `Grammar` object. Additionally `generate_c.rb` is missing several referenced variables:
  - `function_definition_pattern`
  - `probably_a_parameter_2_groups`
  - `operator_overload_4_groups`
  - `variable_name_without_bounds`
  - `non_primitive_types`
  - `primitive_types`

This issue precludes fixing issues in the C grammar.

**Comment by jeff-hykin** [comment]
Yeah, so far all of the changes have essentially been for C++, that file was created for the future. This issue should stay open until there is a proper c-generator file.
