### ISSUE TITLE
Syntax causes tokenization to break for remainder of file

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#488]
Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```
Test::Test() : Base ("{}") {
   // Broken syntax highlight
}
```

## It looks like:
![image](https://user-images.githubusercontent.com/38270282/87306981-242cee00-c519-11ea-9b2f-02b175b6746f.png)

## It should look like:
It looks like things start to go wrong on the first curly brace, which ends up with these scopes:
```
punctuation.section.block.begin.bracket.curly.function.definition.special.constructor.cpp
meta.head.function.definition.special.constructor.cpp
meta.function.definition.special.constructor.cpp
source.cpp
```

**Comment by jeff-hykin** [comment]
Does this code use macros?

**Comment by marzojr** [comment]
The code does not use macros or the preprocessor in any way and is perfectly valid in all versions of c++ ever; here is a full example that compiles:

```c++
struct Base {
    Base(const char *s_);
    const char *s;
};

struct Test : public Base {
    Test();
};

Base::Base(const char *s_) : s(s_) {}

Test::Test() : Base ("{}") {
   // Broken syntax highlight
}
```

You can place it on a c++ file and compile with any compiler.

**Comment by matter123** [comment]
@jeff-hykin constructors are allowed to call other constructors or the base constructor in the initializer list.

This is no different than
```
class Test {
std::string _member;
Test();
}

Test::Test(): _member("{}") {
}
```

Though both highlight correctly for me (if you ignore bracket highlighter getting confused)

![Screen Shot 2020-07-14 at 11 10 26](https://user-images.githubusercontent.com/714007/87461128-d076df00-c5c2-11ea-8102-d661e28f6527.png)

**Comment by marzojr** [comment]
@matter123 It will break highlight if you add a space between `_member` and `(`. It seems like adding a space there combines with the curly braces in the string to break the highlighting.

**Comment by matter123** [comment]
@marzojr It seems that this may have been fixed sometime between the most recently published version and the version that vscode is using. You can manually install the "Better C++ Syntax" extension, to fix for now.

I finally, somewhat, have some time I can put into looking into #460, so hopefully, at some point, the version vscode is using should be able to be updated again.

![Screen Shot 2020-07-14 at 11 16 27](https://user-images.githubusercontent.com/714007/87461736-ab36a080-c5c3-11ea-864a-90b1ec27660e.png)

**Comment by marzojr** [comment]
@matter123 I tried the extension you mentioned, and it does make the problem much better -- but it is still there.

Note that the curly braces in your screenshot are all highlighted as brackets, not as characters inside a character literal. Also, the closing parenthesis of the initializer, as well as the curly braces of the constructor, are incorrectly highlighted.

Exploring a bit, most of the syntax highlighting is correct with that extension, but curly braces, square brackets, and parenthesis, are all incorrectly highlighted for the remainder of the file -- they highlight as brackets while inside strings, and are not highlighted outside of strings.

Interestingly, changing from `{}` to `{}[]` in the character literal will fix the highlighting, probably because the grammar probably identifies it as a lambda introducer instead of as a scope.

**Comment by matter123** [comment]
Are your brackets colored via your color theme or via an extension like "Bracket Pair Colorizer 2"?

If you use "Developer: Inspect Editor Tokens and Scopes", you should see that the grammar correctly marks the "{}" as `string.quoted.double.cpp`

**Comment by marzojr** [comment]
Hm, nice catch; the incorrect bracket highlighting is coming from "Bracker Pair Colorizer 2", and with it disabled, it seems that "Better C++ Syntax" fixes this issue.

**Comment by matter123** [comment]
Closing this as this is fixed in a released version.

**Comment by jeff-hykin** [comment]
Thanks for taking care of this.

And well, I guess consider me surprised, I didn't consider the case of an external initializer list. I guess I'm a bit too used to inline constructors.
