### ISSUE TITLE
Inconsistent syntax for deleted function

### ISSUE THREAD

**Issue by a5066987** [jeff-hykin/cpp-textmate-grammar#496]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```cpp
class MemTable{
public:
  MemTable(const MemTable&) = delete;
  MemTable& operator=(const MemTable&) = delete;
};
```

## It looks like:
![image](https://user-images.githubusercontent.com/13390857/90951534-a52cae80-e410-11ea-9789-33771178c9fe.png)
![image](https://user-images.githubusercontent.com/13390857/90951563-d6a57a00-e410-11ea-892a-eb75efc9e2ea.png)

## It should look like:
I think these two "delete" should be identical.

**Comment by jeff-hykin** [comment]
Should be fixed now (`v1.15.24` released just now), but let me know if it persists
