### ISSUE TITLE
Single digit numbers have different color than multi digit numbers.

### ISSUE THREAD

**Issue by JayXon** [jeff-hykin/cpp-textmate-grammar#5]
![image](https://user-images.githubusercontent.com/1552641/53475662-7481e800-3aab-11e9-8f7a-6e4506c18c1a.png)

**Comment by jeff-hykin** [comment]
Thanks for reporting this. This is a bug I let slip through with the most recent update (adding support for C++14.
It should be fixed now, let me know if there are any similar issues with literals.

**Comment by JayXon** [comment]
Thanks! Looks like you might need some unit test for the regex to avoid regression in the future.

**Comment by jeff-hykin** [comment]
Yup I definitely do.
