### ISSUE TITLE
[[attributes]] break syntax highlighting until `{`

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#50]
Similar to #37 after a C++ attribute `[[fallthrough]]`,`[[nodiscard]]`, etc. Syntax highlighting breaks until `{`.

Example
```
switch(test) {
	case 1:
	break;
	case 2: [[fallthrough]];
	case 3: break; // no syntax highlighting
}
void func1();
[[noreturn]] void func2(/*syntax highlighting*/); // no syntax highlighting
struct st { // syntax highlighting works now
};
void func3();
```
Image:
![Screenshot from 2019-04-01 19-53-11](https://user-images.githubusercontent.com/714007/55372819-db822a80-54b7-11e9-8931-6d7524beb573.png)

**Comment by matter123** [comment]
[[attributes]] are technically ambiguous as
`foo[[]{return funcReturningVector()}()[0]]` is a valid expression. But attributes are far more comman than a self executing lambda inside a subscript operator.

**Comment by jeff-hykin** [comment]
Putting this here just for reference:
https://en.cppreference.com/w/cpp/language/attributes

I think the best way to match it is going to be to create a pattern/range for it and then give it higher priority than lambdas.

If a lambda inside of a subscript operator is the only situation where `[[` is not an attribute, then I think we can safely create a range for attributes.

**Comment by matter123** [comment]
A lambda with a structured bind in the capture is ambiguous if you use a range.

`[[a,b]=foo]{}

**Comment by jeff-hykin** [comment]
Great find 👍  It shouldn't be too hard to implement.

I need to focus on academics till the end of the semester so it might be awhile before I do any major contributions.

**Comment by matter123** [comment]
I came up with
```ruby
#
# C++ Attributes
#
attributes = Range.new(
    repository_name: "attributes_cpp",
    tag_as: "support.other.attribute",
    start_pattern: newPattern(
        match: /\[\[/.or(/__attribute__\(\(/).or(/__declspec\(/),
        tag_as: "punctuation.start.attribute",
    ),
    end_pattern: newPattern(
        match: /\]\]/.or(/\)\)/).or(/\)/),
        tag_as: "punctuation.end.attribute",
    ),
    includes: [
        # allow nested attributes
        "#attributes_cpp",
        Range.new(
            start_pattern: newPattern(/\(/),
            end_pattern: newPattern(/\)/),
            includes: [
                "#strings_c",
            ],
        ),
        newPattern(match: /,/, tag_as: "punctuation.separator.attribute"),
        newPattern(match: /::/, tag_as: "punctuation.accessor.attribute"),
    ],
)
```
However, I can't seem to actually give it a higher priority than the lambda. Even when it is the first pattern, attributes are still tagged as lambdas.

**Comment by matter123** [comment]
It seems that function attributes in namespaces are the issue.

Image:
![Screenshot from 2019-04-03 16-31-02](https://user-images.githubusercontent.com/714007/55519782-19a15a80-562e-11e9-9534-00bcf9aa8800.png)

Unsurprisingly even without the issues caused by namespace, some patterns need to be adjusted to account for [[attributes]].

**Comment by jeff-hykin** [comment]
So I guess this will be decently hard to implement. If the C++ reference has enough documentation we can probably create a check list and gradually add it to each area one by one.

**Comment by matter123** [comment]
I've had some luck with an non greedy non range rule that includes the range rule. I'll make a PR laster today to discuss specifics.

**Comment by peaceshi** [comment]
![image](https://user-images.githubusercontent.com/10380828/55676318-a2a5e380-5905-11e9-8678-484c04329c0b.png)
 Same problem.

**Comment by matter123** [comment]
@peaceshi If you want a fix for some attributes you can copy the json file from #54 https://raw.githubusercontent.com/jeff-hykin/cpp-textmate-grammar/Fix-%2350/syntaxes/cpp.tmLanguage.json into `{your vscode data dir}/extensions/jeff-hykin.better-cpp-syntax-1.6.8/syntaxes` and reload.
