### ISSUE TITLE
Wrong highlighting of hex escape sequences in character and string literal

### ISSUE THREAD

**Issue by WEGFan** [jeff-hykin/cpp-textmate-grammar#501]
Checklist

- [X] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [X] This bug exists for C
- [X] This bug exists for C++
- [ ] This bug exists for Objective-C **(I don't use it so I'm not sure)**
- [ ] This bug exists for Objective-C++ **(I don't use it so I'm not sure)**

## The code with a problem is:
```
'\x12345';
"\x1234aaafg\x1ffh";
"\x123ggg";
```

As <https://timsong-cpp.github.io/cppwp/lex.ccon#7> states:
> The escape \xhhh consists of the backslash followed by x followed by one or more hexadecimal digits that are taken to specify the value of the desired character.
There is no limit to the number of digits in a hexadecimal sequence.
A sequence of octal or hexadecimal digits is terminated by the first character that is not an octal digit or a hexadecimal digit, respectively.

So the highlighting should ends at the last valid hexadecimal digit, not the second.

## It looks like:
![](https://user-images.githubusercontent.com/7558201/93015244-73ab9b00-f5ea-11ea-95cf-2b3dd31b9f00.png)

## It should look like:
![](https://user-images.githubusercontent.com/7558201/93015773-ba02f900-f5ee-11ea-82f9-7e226f94c74f.png)

**Comment by jeff-hykin** [comment]
![Screen Shot 2020-11-03 at 5 58 12 PM](https://user-images.githubusercontent.com/17692058/98053475-3c918300-1dfe-11eb-98c2-701eefff4deb.png)
https://en.cppreference.com/w/cpp/language/escape

My understanding is that the current value is correct, but if you have documentation that shows otherwise I'll take a look.

**Comment by jeff-hykin** [comment]
So far as I can tell it is useless to have (can't go above `\xff` can only have leading zeros `\x000ff`) but if its supported by the spec I suppose it should be colored that way as well.

Here's a version than compiles on clang 9

        auto a = '\x00000';
        cout << "a = " << (a) << "\n";
        auto b = "\x00000f0g\x0000";
        cout << "b = " << (b) << "\n";
        auto c = "\x0012ggg";
        cout << "c = " << (c) << "\n

**Comment by jeff-hykin** [comment]
Deed has been done. Download version `1.15.3` of the extension to get the fix immediately 👍
