### ISSUE TITLE
Inconsistent syntax highlighting for multi line macro function (#define)

### ISSUE THREAD

**Issue by sean-mcmanus** [jeff-hykin/cpp-textmate-grammar#502]
I searched, but couldn't tell if this was a duplicate or not.

Checklist

- [X] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [?] This bug exists for C
- [X] This bug exists for C++
- [?] This bug exists for Objective-C
- [?] This bug exists for Objective-C++

## The code with a problem is:
```
#define KEYMAP( \
      k00, k01, k02, k03, k04, k05, k06, \
      k10, k11, k12, k13, k14, k15, k16, \
      k20, k21, k22, k23, k24, k25, k26, \
      k30, k31, k32, k33, k34, k35,  k36 \
) \
{ \
    { k06, k05, k04, k03, k02, k01, k00 }, \
    { k16, k15, k14, k13, k12, k11, k10 }, \
    { k26, k25, k24, k23, k22, k21, k20 }, \
    { k36, k35, k34, k33, k32, k31, k30 } \
}
```

## It looks like:
** screenshot + theme name preferable **
Dark+ Theme:
![image](https://user-images.githubusercontent.com/19859882/94465197-61963480-0174-11eb-9551-92fd649e485d.png)

## It should look like:
Consistent in regards to the k variables and the `\`.

Repro is from https://github.com/microsoft/vscode-cpptools/issues/6217 .

**Comment by jeff-hykin** [comment]
fixed with 1.15.2 👍
