### ISSUE TITLE
Identifiers incorrectly categorized

### ISSUE THREAD

**Issue by longnguyen2004** [jeff-hykin/cpp-textmate-grammar#508]
Consider this code snippet:
```
// Assignment
fs::path path1 = obj->Path;

// Uniform initialization
fs::path path2{obj->Path};

// Old style initialization
fs::path path3(obj->Path);
```

`path1` and `path2` are incorrectly linked to the previous token `path`, which causes them to not be categorized
![image](https://user-images.githubusercontent.com/15729831/95479144-a1e78500-09b4-11eb-871e-761c0cdef64f.png)

`path3` is incorrectly categorized as a function definition, which causes the arrow operator to be split into two (represented by missing arrow ligatures). Seems like we've encountered the Most Vexing Parse again.
![image](https://user-images.githubusercontent.com/15729831/95479281-cb081580-09b4-11eb-86a1-2720111172b0.png)

**Comment by jeff-hykin** [comment]
Finally @sean-mcmanus / @Colengms I think this one is for you guys. (I'm not sure where to categorize it)

**Comment by sean-mcmanus** [comment]
@longnguyen2004 I'm not reproing the bug (with our pending 1.1.0-insiders4 release). Can you file a bug at https://github.com/microsoft/vscode-cpptools/issues with more repro info?

![image](https://user-images.githubusercontent.com/19859882/98056852-c426c400-1df5-11eb-9e3b-b299b457b545.png)

**Comment by jeff-hykin** [comment]
(thanks @sean-mcmanus)

**Comment by longnguyen2004** [comment]
Hmm let me see again, maybe it has been fixed at some point.

**Comment by sean-mcmanus** [comment]
@longnguyen2004 The colorization in your screenshot indicates that semantic colorization is not being used. I think the incorrect lexical colorization for path3 is expected.
