### ISSUE TITLE
parentheses getting different scopes

### ISSUE THREAD

**Issue by mxdh** [jeff-hykin/cpp-textmate-grammar#513]
Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [X] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```
#define NULL ((void *)0)
```

## It looks like:
![屏幕截图 2020-10-21 191555](https://user-images.githubusercontent.com/20399194/96860234-15998f80-1495-11eb-806e-d6a1121f2b76.png)
![屏幕截图 2020-10-21 191751](https://user-images.githubusercontent.com/20399194/96860253-1d593400-1495-11eb-8b19-1628a15112f2.png)
![屏幕截图 2020-10-21 191814](https://user-images.githubusercontent.com/20399194/96860265-20542480-1495-11eb-8d91-edc4bf023318.png)
Cold Horizon

## It should look like:
Sorry,I'm not good at English.
I think these parentheses should have consistent scopes, at least each pair of parentheses should match each other.

Originally from https://github.com/microsoft/vscode-cpptools/issues/6365

**Comment by jeff-hykin** [comment]
Fixed 👍 . Install the extension (version 1.15.1) to get the fix immediately. Or wait till the next VS Code release (or two)!
