### ISSUE TITLE
Character literal of percent sign ('%') triggers string highlighting run-on

### ISSUE THREAD

**Issue by rlee287** [jeff-hykin/cpp-textmate-grammar#515]
(I am assuming based on "This used to be a fix, but then VS Code starting using it as the official source for C and C++ highlighting" that this is the correct repository to use when reporting default VS Code syntax highlighting bugs for C/C++, so please redirect me to the correct repository if I should be reporting this bug somewhere else.)

Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"` (N/A?)
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```cpp
#include <iostream>

std::string identity_string_func(std::string input) {
    return input;
}

int main(int argc, char ** argv) {
    // Percent sign triggers highlighting bug
    std::string test = '%' + identity_string_func("blah");
    std::cout << test;
}
```

## It looks like:
Default Dark+, VS Code 1.50.1:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/14067959/97766089-3041b900-1ad2-11eb-859c-2f20799532a2.png">

## It should look like:
String highlighting color should not extend past the end of `'%'`.

## Additional Notes:
This syntax highlighting issue occurs whether the Microsoft C/C++ Extension to VS Code is enabled or disabled.

**Comment by jeff-hykin** [comment]
hi Ryan, yup you're in the right place (good job, its not always easy to find).

This is surprising as that bug should have been fixed awhile ago. If you install the extension it will give you the latest version of the syntax and should fix the problem. 
![code](https://user-images.githubusercontent.com/17692058/97778500-a29fb100-1b45-11eb-9693-3682593bed69.png)

I'll have to look into why this fix isn't in VS Code.

(I'll reopen this issue if you're still having problems, but installing the extension should fix it)

**Comment by rlee287** [comment]
Installing the extension fixed the bug. Please let me know if you find anything about putting this fix into the syntax highlighting built into VS Code.
