### ISSUE TITLE
Incorrect scope with single quotes in template

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#516]
Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```cpp
template<int N, char ...chs> struct formater_generator : formater_generator<N-1, '{', '}', chs... > {};
```

## It looks like:
![image](https://user-images.githubusercontent.com/38270282/97859899-88aacd80-1d01-11eb-9713-cdad2cfc6082.png)

## It should look like:
The second `'` in `'{'` is incorrectly getting scoped as the start of a string.

Originally posted by @zwkno1 in https://github.com/microsoft/vscode/issues/109798

**Comment by jeff-hykin** [comment]
![code](https://user-images.githubusercontent.com/17692058/98052321-82991780-1dfb-11eb-9610-f6196194767e.png)

Fixed in latest I believe
