### ISSUE TITLE
Color Theme for C++ Class Object

### ISSUE THREAD

**Issue by sstaub** [jeff-hykin/cpp-textmate-grammar#517]
Checklist

- [x] This bug exists for C++

Using VSCode with PlatformIO
The color of a class object (e.g. MyClass myObject) in C++ is interpreted as the color of a variable ("scope": "variable").
It should possible to give the class objects their own color definition in the color theme .json file
The same for the class method, in the moment the color of a class method is the same as the color for a function.
It will help to differ methods from functions

Here some screenshot for better understanding:
first I use a grey color for the scope "variable", then red for the second example.
<img width="352" alt="94548100-8364e980-0250-11eb-91f6-a1f6a295128f" src="https://user-images.githubusercontent.com/6450325/98352870-de8fb600-201e-11eb-8c4f-129a03be3204.png">
<img width="352" alt="94548166-9b3c6d80-0250-11eb-8d70-9efc0fae0eab" src="https://user-images.githubusercontent.com/6450325/98353130-2d3d5000-201f-11eb-869a-0477d720e8cb.png">

here what happens in the code when 'variable' is grey:
<img width="416" alt="94548243-b60ee200-0250-11eb-8d42-9742ec02934c" src="https://user-images.githubusercontent.com/6450325/98352898-e6e7f100-201e-11eb-8c39-ed0b132c1c99.png">
now when red:
<img width="426" alt="94548271-c45cfe00-0250-11eb-8714-5d7e97ef88ce" src="https://user-images.githubusercontent.com/6450325/98352916-ec453b80-201e-11eb-859e-4a51a337477f.png">
The color of the green marked 'variable' is changing together with cyan marked 'class object'.
I would expect that a 'class object' has a different color.
The same for the orange marked 'functions', the first function is real single 'function', the second one
is also a function but also a 'class member', therefore there should also different colors.

**Comment by sstaub** [comment]
see also the original issue https://github.com/microsoft/vscode/issues/105675

**Comment by matter123** [comment]
There should be some difference in the scope between the different colored boxes you can use the command palpate action `> Developer: Inspect Editor Tokens and Scopes` to examine the scope. However due to how textmate grammars work it's not always possible to determine the correct scope for each token. You may want to try the semantic coloring for the C/C++ extension.
