### ISSUE TITLE
Incorrect color in multi comments with \sa

### ISSUE THREAD

**Issue by xiaoma20082008** [jeff-hykin/cpp-textmate-grammar#519]
Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```c++
class Test {
private:
int a; /**
\sa
*/
int b; /*
\sa
*/
}
```

## It looks like:

![image](https://user-images.githubusercontent.com/10076393/98905143-e1464b80-24f5-11eb-9436-b47a8c644e45.png)

## It should look like:
no spacial keywords in comments

From [microsoft/vscode-cpptools/issues/6108](https://github.com/microsoft/vscode-cpptools/issues/6108#issuecomment-725390997) and 
[microsoft/vscode-cpptools/issues/6108](https://github.com/microsoft/vscode-cpptools/issues/6108#issuecomment-725666737)

**Comment by matter123** [comment]
This is as intended as `\sa` is a doxygen command.

@jeff-hykin Doxygen support seems at least a little contriversial with several issues about it.

The following issues complain about doxygen support
- #450
- #495
- #519

While the following issues are in favor of keeping/expanding doxygen support
- #353
- #418
- #449
- #499

Would it be worthwhile to publish a version that does not have extended support for any type of documentation comments?

**Comment by jeff-hykin** [comment]
> Would it be worthwhile to publish a version that does not have extended support for any type of documentation comments?

Yeah I think it would be worthwhile to publish multiple versions of the C++ syntax. There have been some issues with ASM integration too. It'd be really nice if we could supply both a grammar and injections that could be toggled but I think that isn't allowed by default and would be a lot of work as a workaround.

I think we could just start off with 
`C++ -- extended (ASM, Doxygen, SQL, Regex)`
and `C++ -- pure`
