### ISSUE TITLE
Base classes without access specifier not tagged.

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#53]
Example code:
```c++
class foo : bar {};
class foo : public bar {};
```
One line 1 `bar` has the scope `meta.class-struct-block.cpp source.cpp`.
One line 2 `bar` has the scope `entity.name.type.inherited.cpp meta.class-struct-block.cpp source.cpp`.
The scope for `bar` on each line should be identical.
This is not a regression, and the issue existed prior to #49.

**Comment by jeff-hykin** [comment]
Fixed with `v1.8.1`
