### ISSUE TITLE
Some keywords are not recognized

### ISSUE THREAD

**Issue by mmatrosov** [jeff-hykin/cpp-textmate-grammar#535]
Checklist

- [X] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [X] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```
using T = const int;
using U = void;
```

```
{
  "workbench.colorTheme": "Visual Studio Dark - C++",
  "editor.tokenColorCustomizations": {
    "[Visual Studio Dark - C++]": {
      "keywords": "#fafa47"
    }
  }
}
```

## It looks like:
![image](https://user-images.githubusercontent.com/3617951/106888161-3a89d980-66f7-11eb-87ec-40c702922c2b.png)

## It should look like:
All keywords should be yellow.

## Comments
Originally posted here: https://github.com/microsoft/vscode-cpptools/issues/6904, but then I was redirected to this project.

**Comment by jeff-hykin** [comment]
Thats a problem with the theme, `const` is tagged as a storage modifier . [Here's a guide](https://jeffhykin.medium.com/how-to-customize-your-vs-code-text-colors-c0191155f41a) I made for overriding your theme.

**Comment by mmatrosov** [comment]
Hi, @jeff-hykin. I fixed my issue with this method, but the fix looks kind of ugly. Here is the list of scopes I added to the config:

```
          "scope": [
            "keyword.operator.cast.const_cast.cpp",
            "keyword.operator.cast.dynamic_cast.cpp",
            "keyword.operator.cast.reinterpret_cast.cpp",
            "keyword.operator.cast.static_cast.cpp",
            "keyword.operator.delete.cpp",
            "keyword.operator.new.cpp",
            "keyword.other.default.constructor.cpp",
            "keyword.other.operator.overload.cpp",
            "keyword.other.using.directive.cpp",
            "storage.modifier.cpp",
            "storage.modifier.inline.cpp",
            "storage.modifier.lambda.mutable.cpp",
            "storage.modifier.specifier.const.cpp",
            "storage.modifier.specifier.functional.post-parameters.const.cpp",
            "storage.modifier.specifier.functional.post-parameters.final.cpp",
            "storage.modifier.specifier.functional.post-parameters.override.cpp",
            "storage.modifier.specifier.functional.pre-parameters.constexpr.cpp",
            "storage.modifier.specifier.functional.pre-parameters.explicit.cpp",
            "storage.modifier.specifier.functional.pre-parameters.inline.cpp",
            "storage.modifier.specifier.functional.pre-parameters.mutable.cpp",
            "storage.modifier.specifier.functional.pre-parameters.virtual.cpp",
            "storage.modifier.specifier.static.cpp",
            "storage.modifier.static.cpp",
            "storage.modifier.virtual.cpp",
            "variable.language.this.cpp",
          ],
```

This is a lot, and I'm quite sure this list is not exhaustive. Is there a way for the users not to hand-craft such list? On which side this should be addressed?

**Comment by jeff-hykin** [comment]
Welcome to the wonderful world of Themeing haha. Lovely isn't it? I do have some practical answers, but no; there is no generic practical way to know if it exhaustive, and there is no standard (different for every language). People, and I'm one of them, have been working to improve this situation, especially on for Atom (which is more accepting of improvements) and uh... we haven't made it very far.

One exception is ✨ this C++ repo ✨ there is a [file here](https://github.com/jeff-hykin/cpp-textmate-grammar/blob/71aa94cca719713f4358f70b7f46f6a1689d2de1/source/languages/cpp/language_tags.txt) that is auto generate every time we edit the syntax grammar, and it is completely comprehensive.

BUT before you go listing a million different scopes, read this

`storage.modifier` => blue
`storage.modifier.specifier` => green
`source.cpp storage.modifier.specifier` (<- note the space in there) => yellow 

Would be parsed as
color all `storage.modifier` blue
UNLESS its `storage.modifier.specifier` then color it green
UNLESS its `storage.modifier.specifier` inside a `source.cpp` then color it yellow

Dont forget: your theme has these rules too. So if the theme has `storage.modifier.specifier` then you need to specify `source storage.modifier.specifier` or `storage.modifier.specifier.SOMETHING` to override it

Languages usually have `source.EXTENSION`... again usually.

**Comment by mmatrosov** [comment]
Hi, Jeff! Thanks a lot for an elaborate answer! It was not at all obvious that I can replace `foo.bar.cpp` with `source.cpp foo.bar` allowing for the suffix matching. I made my list a lot shorter with this trick, thanks!

There is one thing I fail to understand though. Let's consider the `static_cast` keyword. The default color for it is blue. But since I want my keywords to be yellow, I set yellow for `source.cpp keyword.operator.cast.static_cast`. It works. Then I generalize the scope by stripping off the last part and something strange happens:

* If I set `source.cpp keyword.operator.cast.static_cast` to yellow then `staic_cast` is yellow
* If I set `source.cpp keyword.operator.cast` to yellow then `staic_cast` is yellow
* If I set `source.cpp keyword.operator` to yellow then `staic_cast` is blue
* If I set `source.cpp keyword` to yellow then `staic_cast` is blue

So it seems as if `source.cpp keyword.operator.cast` is defined somewhere else to be blue. But I don't define it anywhere. And it is not defined in the default config. What's happening?

**Comment by jeff-hykin** [comment]
Oh good job posting that issue on the C++ tools, I forgot about that caveat.

VS Code allows extensions to override the normal themes as you're finding out. And it's kind of hacky because it doesn't show up when you inspect the scopes.

Even though I helped them decide on what scope names to use, because of the overriding nature of the extension I eventually turned enhanced colors off just because it was too hard to figure out how to get them to work with my theme

**Comment by Colengms** [comment]
Hi @jeff-hykin @mmatrosov .  FYI, the C/C++ Extension now uses VS Code's Semantic Tokens API for 'enhanced colorization', so we are no longer interpreting or overriding any TextMate scopes, or applying any colorization (text decorations) ourselves.  We output semantic tokens.  We do provide a mapping to allow VS Code to apply the colors of our prior TextMate scopes, if no color was set for the semantic token, for backwards compatibility.  But, at this point, all colors are applied by VS Code, all scope cascading is done by VS Code, and all color values are coming from either a Theme or VS Code.

The fallback scopes from our package.json are below.  Any semantic tokens not listed here don't have fallback scopes.  I don't think our current implementation would cause issues with `keyword.operator` or `keyword.operator.cast`, as we don't directly refer to either.

```
    "semanticTokenScopes": [
      {
        "scopes": {
          "label": [
            "entity.name.label"
          ],
          "variable.global": [
            "variable.other.global"
          ],
          "variable.local": [
            "variable.other.local"
          ],
          "property.static": [
            "variable.other.property.static"
          ],
          "method.static": [
            "entity.name.function.member.static"
          ],
          "macro": [
            "entity.name.function.preprocessor"
          ],
          "referenceType": [
            "entity.name.type.class.reference"
          ],
          "cliProperty": [
            "variable.other.property.cli"
          ],
          "genericType": [
            "entity.name.type.class.generic"
          ],
          "valueType": [
            "entity.name.type.class.value"
          ],
          "templateFunction": [
            "entity.name.function.templated"
          ],
          "templateType": [
            "entity.name.type.class.templated"
          ],
          "operatorOverload": [
            "entity.name.function.operator"
          ],
          "memberOperatorOverload": [
            "entity.name.function.operator.member"
          ],
          "newOperator": [
            "keyword.operator.new"
          ],
          "numberLiteral": [
            "entity.name.operator.custom-literal.number"
          ],
          "customLiteral": [
            "entity.name.operator.custom-literal"
          ],
          "stringLiteral": [
            "entity.name.operator.custom-literal.string"
          ]
        }
      }
```

**Comment by mmatrosov** [comment]
Thanks, @Colengms. So is there any way to find out why do I have this strange behavior with the colors depending on the scopes?

**Comment by jeff-hykin** [comment]
@Colengms thanks for the update! I didn't realize the semantic highlighting didn't use TextMate tokens, which is my bad. Looks like I need to do some research to get up to date
