### ISSUE TITLE
Objective c: self, super, and _cmd are not syntax highlighted at all

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#538]
Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [ ] This bug exists for C++
- [x] This bug exists for Objective-C
- [x] This bug exists for Objective-C++

OS version: Darwin x64 19.5.0

I noticed that in the Objective-C language, special variables (`#special_variables`) like `self`, `super`, and `_cmd` are not syntax highlighted at all. I also noticed that method calls are not syntax highlighted either, unlike regular C-style function calls.

After some digging around in the `.tmLanguage` file for Objc, I noticed that if I add a top-level include for the `#special_variables` repository and copy the declaration for `meta.function-call.objc` to the top level as well, both are syntax highlighted.

The default rendering:
![Original](https://user-images.githubusercontent.com/8371943/107847899-f791cb00-6db4-11eb-9467-1b1a5285755d.png)

With a duplicate top-level decl for `meta.function-call.objc`:
![With special_variables](https://user-images.githubusercontent.com/8371943/107847901-fe204280-6db4-11eb-8d01-8a8fab9b4879.png)

With the above, and `#special_variables` included:
![Screenshot 2021-02-13 at 4 31 14 AM](https://user-images.githubusercontent.com/8371943/107847924-3162d180-6db5-11eb-9513-cba38be37274.png)

Originally from @NSExceptional in https://github.com/microsoft/vscode/issues/116612

**Comment by jeff-hykin** [comment]
@NSExceptional I appreciate your research by the way 😁 
It might be a little bit before I can get to this, but I'll keep an eye on it and if any PR's are made I'll can review an merge them.

@NSExceptional Obj-C/C++ have not received much love since I'm not not terribly familiar with the syntax (and I don't think Matter123 is either)

**Comment by NSExceptional** [comment]
Hi all,

Objc code syntax highlights much more correctly in TextMate, which is what makes me think this is a bug with VS Code, and not an error in the grammar.

<img width="306" alt="Screenshot 2021-02-22 at 3 29 01 PM" src="https://user-images.githubusercontent.com/8371943/108772516-b4f19080-7522-11eb-904f-a83ac0a8117c.png">

**Comment by DavidGoldman** [comment]
I believe https://github.com/jeff-hykin/cpp-textmate-grammar/blob/master/syntaxes/objc.tmLanguage.json is forked/divergent from  https://github.com/textmate/objective-c.tmbundle/blob/master/Syntaxes/Objective-C.tmLanguage (which is more up to date)

**Comment by DavidGoldman** [comment]
@NSExceptional You can use the `Developer: Inspect Editor Tokens and Scopes` command to view the textmate scopes for keywords (e.g. `self`), but it's likely an issue with the grammar

**Comment by NSExceptional** [comment]
Ah. Should we try to merge in the textmate fork then?

**Comment by DavidGoldman** [comment]
Yep, that makes sense to me, just need to make sure that the objc++ grammar still works well.

**Comment by DavidGoldman** [comment]
@alexr00 Can you merge this change into VS Code? Doesn't seem to have been pulled in yet: https://github.com/microsoft/vscode/tree/main/extensions/objective-c

**Comment by alexr00** [comment]
@DavidGoldman updated, thanks for the ping (we had a bug in our update script for objective c).
