### ISSUE TITLE
enum bug: punctuation.inhertance.colon.cpp

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#55]
set:
![image](https://user-images.githubusercontent.com/10380828/55676395-42b03c80-5907-11e9-9364-4c2fcfbe8528.png)
then
![image](https://user-images.githubusercontent.com/10380828/55676399-59569380-5907-11e9-9072-1879c3c597f8.png)
![image](https://user-images.githubusercontent.com/10380828/55676401-64112880-5907-11e9-9212-fe3373d13049.png)

**Comment by matter123** [comment]
Can you provide some example code?

**Comment by peaceshi** [comment]
> Can you provide some example code?

https://github.com/lhmouse/asteria/blob/master/asteria/src/syntax/statement.hpp

**Comment by matter123** [comment]
well `punctuation.inheritance.colon` is probably better as `punctuation.type-specifier.colon` (@jeff-hykin ?).

I am not sure that the colon selected in the hover is an issue with this grammar. enum names are unscoped [decl.enum]/1. vscode-cpptools is doing something odd.

**Comment by peaceshi** [comment]
> well `punctuation.inheritance.colon` is probably better as `punctuation.type-specifier.colon` (@jeff-hykin ?).tokenColorCustomizations` to hide the issue, see #7 for more information.
> 
> I am not sure that the colon selected in the hover is an issue with this grammar. enum names are unscoped [decl.enum]/1. vscode-cpptools is doing something odd.
> 
> You can use the setting `editor.

yeah, just I use `tokenColorCustomizations`, then discover this intesting bug.

**Comment by matter123** [comment]
the slightly wrong scope is because #49 combined `class`,`struct`,`enum` and `union` all under one pattern, but `enum` uses the colon slightly differently.

**Comment by matter123** [comment]
The scope should be more appropriate once #57 is accepted.

**Comment by jeff-hykin** [comment]
I think `punctuation.type-specifier.colon` is good name. I'll try to get that merged in by tonight.

**Comment by jeff-hykin** [comment]
This should be fixed by the next version, which should be pushed tonight. Let me know if it it's not fixed.
