### ISSUE TITLE
C++ syntax highlightning for function identifiers works with spaces but breaks with newline

### ISSUE THREAD

**Issue by madeso** [jeff-hykin/cpp-textmate-grammar#556]
## Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
(I'm pretty sure I tested this and managed to repro, but vs code doesn't recognize the option anymore)
- [x] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
(not tested)
- [ ] This bug exists for Objective-C++
(not tested)

## The code with a problem is:
```cpp
// no issue
void foo ();

// issue
void bar
();
```

## It looks like:
(solarized light if it matters)

![image](https://user-images.githubusercontent.com/1352934/122916975-ca09ef00-d35d-11eb-8b1f-aecd96b9e486.png)

## It should look like:
![image](https://user-images.githubusercontent.com/1352934/122916924-b8284c00-d35d-11eb-9be7-6c6991fa40b2.png)
(with the newline obvsiously)

**Comment by msftrncs** [comment]
This is unfortunately a limitation between TextMate and this strict format grammar interpretation.   You must move the `(` to the same line as the function name for this grammar (and generally any based on TextMate) to correctly scope the function.

**Comment by jeff-hykin** [comment]
Sadly msftrncs is right. There's no foolproof way to handle this without VS Code upgrading it's parsing engine to be the Tree Sitter parser. 

The only way to make it work would be to use the first line to "guess" that it's a function definition and not something else.
