### ISSUE TITLE
template bug : angle-brackets.end.template syntax.

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#56]
`>>`  keyword.operator.bitwise.shift.cpp  
![image](https://user-images.githubusercontent.com/10380828/55676677-7f7e3280-590b-11e9-8676-430eba9ce04e.png)

![image](https://user-images.githubusercontent.com/10380828/55676692-a50b3c00-590b-11e9-8a83-1ba5c91888d7.png)

I think vsc team should  solve this, maybe.

**Comment by matter123** [comment]
Duplicate of #33.
