### ISSUE TITLE
Typedefs with bool in the name highlighted incorrectly.

### ISSUE THREAD

**Issue by ThadHouse** [jeff-hykin/cpp-textmate-grammar#58]
![CppBool](https://user-images.githubusercontent.com/7727148/55678570-03ef9780-58b1-11e9-9284-4bc17014686f.PNG)

This highlighting is incorrect, and having the 2 different ways of highlighting on the same token is very distracting.

**Comment by matter123** [comment]
Could you confirm that this happens with 1.6.8? I am unable to reproduce.
![Screenshot from 2019-04-06 21-22-55](https://user-images.githubusercontent.com/714007/55678650-4d8cb200-58b2-11e9-8627-0c483e381699.png)

**Comment by ThadHouse** [comment]
How do I load newer versions into VS Code? They switched to using this as their colorization, which is where I am noticing these issues at.

**Comment by matter123** [comment]
Extension page: https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax
`ext install jeff-hykin.better-cpp-syntax`

**Comment by ThadHouse** [comment]
Thank you. That fixes this.
