### ISSUE TITLE
Weird color for hex numbers

### ISSUE THREAD

**Issue by JayXon** [jeff-hykin/cpp-textmate-grammar#6]
![image](https://user-images.githubusercontent.com/1552641/53475965-40f38d80-3aac-11e9-95ee-908c50e77024.png)

`a-f` have different color than `0-9`, don't think that's intended.

**Comment by jeff-hykin** [comment]
Thanks for posting the issue, the pattern was missing the lowercase letters. This should be fixed now. Let me know if anything is messed up.
