### ISSUE TITLE
static_casts in operator << are not highlighted the same

### ISSUE THREAD

**Issue by ThadHouse** [jeff-hykin/cpp-textmate-grammar#60]
![Inconsistencies](https://user-images.githubusercontent.com/7727148/55678613-78c2d180-58b1-11e9-85ce-c9c0276ee266.PNG)

They need to be highlighted the same, the inconsistencies are distracting.

**Comment by matter123** [comment]
Could you confirm that this happens with 1.6.8? I am unable to reproduce.
![Screenshot from 2019-04-06 21-22-42](https://user-images.githubusercontent.com/714007/55678657-6301dc00-58b2-11e9-8fa1-4b4ba6b2d79c.png)

**Comment by ThadHouse** [comment]
Yes, the updated version in vscode fixes this. Thanks
