### ISSUE TITLE
No color for symbols

### ISSUE THREAD

**Issue by JayXon** [jeff-hykin/cpp-textmate-grammar#7]
This extension
![image](https://user-images.githubusercontent.com/1552641/53556566-145c7600-3b7f-11e9-8bc9-c7df4ba485c7.png)

VSCode default
![image](https://user-images.githubusercontent.com/1552641/53556622-2dfdbd80-3b7f-11e9-8142-ce291c1fb95c.png)

This is a minor issue, but `+`, `*` and `&` all lost its color when using this extension, ideally they should be highlighted with a different color than `int`.

**Comment by jeff-hykin** [comment]
<img width="379" alt="screen shot 2019-02-28 at 5 56 45 am" src="https://user-images.githubusercontent.com/17692058/53564960-d11deb00-3b1d-11e9-9c24-7084f69ae1ab.png">

So I believe this is actually a setting with your theme.
BUT, the good news is VS Code lets you customize absolutely everything.
If you add the following code to your settings.json, it should make them the original color again.
And in fact, if you want, you can set them to whatever color you would like so it can be different than int. (Just change the `"foreground": "#bc7ed7",` part below to change the color)
```json
        "editor.tokenColorCustomizations" : 
            {
                "textMateRules": [
                {
                    "name": "symbol color",
                    "scope": [
                        "source.cpp keyword.operator"
                    ],
                    "settings": {
                        "foreground": "#bc7ed7",
                        "fontStyle": ""
                    }
                }
                ]
            },
```

The only thing this extension does is make sure that the language gets labeled correctly (e.g. strings are marked as 'strings' and operators are marked as 'keyword.operator'). It's then the theme's job to take those names and give them color.

**Comment by jeff-hykin** [comment]
I'm going to keep this issue open for now until I can create a guide for customizing theme colors exactly how you want, because I believe this is going to be a common issue. 

Not only can you change the colors but you can also change things like bold underline and cursive-ness of things. Read this if you want more info https://medium.com/@JeffHykin/how-to-get-cursive-fonts-in-vs-code-2018-without-operator-mono-220544fed93a

**Comment by jeff-hykin** [comment]
Alright, I finally created a simple post for this, feel free to read it [here](https://medium.com/@JeffHykin/how-to-customize-your-vs-code-text-colors-c0191155f41a)
