### ISSUE TITLE
Classes with opening brace on separate line breaks highlighting for rest of file

### ISSUE THREAD

**Issue by Novakov** [jeff-hykin/cpp-textmate-grammar#72]
**VS Code** 1.33.0 
**Better C++ Syntax** 1.7.1
No other extensions installed and default settings

**Code:**
```cpp
class A
{
    void abc();
};
```

**Highlight:**
![image](https://user-images.githubusercontent.com/420393/55901678-20017a80-5bca-11e9-9c5c-59f8e1524c5e.png)

Return type `void` of method `abc` is not highlighted. If I add field it's also just white.

Does this extension require some initial setup (like coloring rules) or should I get nice highlighting just after installing it?

**Comment by matter123** [comment]
I am unable to reproduce. What color theme are you using?
<img width="185" alt="Screen Shot 2019-04-10 at 10 55 00 AM" src="https://user-images.githubusercontent.com/714007/55901963-51088d80-5b7f-11e9-8333-d2ada916acb2.png">

**Comment by Novakov** [comment]
Dark+

What's yours? I will check if it works on my machine

**Comment by matter123** [comment]
I am using
> Name: Horizon Theme
Id: jolaleye.horizon-theme-vscode
Description: A beautifully warm dark theme for Visual Studio Code
Version: 1.8.1
Publisher: Jonathan Olaleye
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=jolaleye.horizon-theme-vscode

**Comment by Novakov** [comment]
Still the same with Horizon Theme. Could you try running code like this:
`code --extensions-dir <tmp>\ext --user-data-dir <tmp>\user`
and then install Better C++ extension?

If it will work then it will mean that my instance is broken

**Comment by matter123** [comment]
Ok i am able to reproduce now

**Comment by matter123** [comment]
Looks like this is a regression from 1.6.8 when the patterns for classes were updated.

**Comment by Novakov** [comment]
Not only classes but `enum class` and `struct` as well (functions are ok). Putting space before curly brace "fixes" highlighting of that class.
![2019-04-10_20-23-19](https://user-images.githubusercontent.com/420393/55903682-85576a80-5bce-11e9-9b31-31807fa48a40.gif)

**Comment by matter123** [comment]
That is extremely helpful, thank you.

**Comment by matter123** [comment]
@jeff-hykin Text mate grammars use single line matches the last character that could possibly be matched is `\n` the pattern on https://github.com/jeff-hykin/cpp-textmate-grammar/blob/master/cpp/generate.rb#L54 could never match a `{` on a new-line.

**Comment by matter123** [comment]
Ok, I have a potential fix.

Could you replace `<vscode extension dir>/jeff-hykin.better-cpp-syntax-1.7.1/syntaxes/cpp.tmLanguage.json` with https://raw.githubusercontent.com/jeff-hykin/cpp-textmate-grammar/Fix-%2372/syntaxes/cpp.tmLanguage.json and give that a try.

<img width="185" alt="Screen Shot 2019-04-10 at 11 50 21 AM" src="https://user-images.githubusercontent.com/714007/55905487-e3605f80-5b86-11e9-8610-17d596aa839e.png">
Make sure to reload vscode `ctrl-shift-p` `Developer: Reload Window`

**Comment by Novakov** [comment]
It's better, kind of...
![2019-04-10_20-53-54](https://user-images.githubusercontent.com/420393/55905690-ccdff580-5bd2-11e9-8c8c-68647c85fec4.gif)

**Comment by matter123** [comment]
Ok, I have another potential fix. URL is the same.

**Comment by Novakov** [comment]
Seems to be working.
However, I don't know if it is related:
![image](https://user-images.githubusercontent.com/420393/55906964-ca32cf80-5bd5-11e9-81e6-f2ee8be5ce45.png)


I think `struct` should be highlighted.

**Comment by matter123** [comment]
It is technically a separate issue but it has the same root cause and is a regression as well so ill add it to the same PR.

**Comment by matter123** [comment]
Ok, that's fixed.

<img width="92" alt="Screen Shot 2019-04-10 at 12 24 09 PM" src="https://user-images.githubusercontent.com/714007/55907439-9fbc2480-5b8b-11e9-8fa1-158acdbcbc54.png">

**Comment by Novakov** [comment]
Awesome! 

But... (I guess now I'm on your list of most annoying people ;))
![2019-04-10_21-26-31](https://user-images.githubusercontent.com/420393/55907599-788b4480-5bd7-11e9-8568-573007355a74.gif)

**Comment by matter123** [comment]
Not at all.
That issue is because `struct A` requires a whitespace character after `struct`. `struct[[nodiscard]]` or `struct{` do not however. The difficult part is `struct[[nodiscard]]A` does not require any whitespace so the whitespace can't just be attached to the name.

**Comment by Novakov** [comment]
I hate grammars ;) It's not really an issue for me. Maybe it would be useful to create page with 'known issues' like this?

**Comment by matter123** [comment]
it is solvable, it just requires a lot of alternations. That's probably a good idea, however.

**Comment by matter123** [comment]
Case in point:
<img width="114" alt="Screen Shot 2019-04-10 at 12 40 19 PM" src="https://user-images.githubusercontent.com/714007/55908285-dd21b180-5b8d-11e9-8665-cd53f7b25cf7.png">

**Comment by jeff-hykin** [comment]
Thanks for both of you guys acting quickly. I was kind of concerned that something like this might happen when I was pushing so many changes last night.

I merged in @matter123 fix and published an updated version of the extension.

**Comment by arzaidi** [comment]
Fix file doesn't exist anymore I think:
 https://raw.githubusercontent.com/jeff-hykin/cpp-textmate-grammar/Fix-%2372/syntaxes/cpp.tmLanguage.json

Please provide working link.
