### ISSUE TITLE
Calling conventions `__cdecl`

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#76]
vscode doesn't know what is `__cdecl` and others.
![image](https://user-images.githubusercontent.com/10380828/55909793-7644dc80-5c0f-11e9-8fe8-deff09432ff1.png)

**Comment by matter123** [comment]
Blocked by #80

**Comment by jeff-hykin** [comment]
Is there a list of things like `__cdecl`?

**Comment by matter123** [comment]
Msvc: https://docs.microsoft.com/en-us/cpp/cpp/argument-passing-and-naming-conventions?view=vs-2019
- __cdecl
- __clrcall
- __stdcall
- __fastcall
- __thiscall
- __vectorcall
