### ISSUE TITLE
struct/class tail needs to allow for variable declaration

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#78]
![image](https://user-images.githubusercontent.com/10380828/55920148-53c0bc80-5c2b-11e9-8082-c3c746b4669c.png)
https://github.com/lhmouse/asteria/blob/master/asteria/src/compiler/token_stream.cpp#L245

**Comment by matter123** [comment]
@jeff-hykin Adding `$base` to `tail_includes` to resolve this should be no worse than `1.6.8` right?

**Comment by jeff-hykin** [comment]
Yeah that should be the quick fix

**Comment by jeff-hykin** [comment]
Wow, I really though that code would have violated the C++ spec, and I can't find anything similar to it in the spec. This was the closest I could find: https://en.cppreference.com/w/cpp/language/declarations

**Comment by jeff-hykin** [comment]
Pushed just now v1.7.3

**Comment by matter123** [comment]
@jeff-hykin Do you mind if I tag the versions?

**Comment by jeff-hykin** [comment]
That would be great!
