### ISSUE TITLE
extern "C" breaks function & variable highlighting

### ISSUE THREAD

**Issue by Novakov** [jeff-hykin/cpp-textmate-grammar#85]
VS Code 1.33.0
Better C++ Syntax 1.7.5
No other extensions installed and default settings

![](https://user-images.githubusercontent.com/420393/55933058-4526d500-5c2c-11e9-82eb-71f9693d3f32.png)

![image](https://user-images.githubusercontent.com/420393/55933635-46590180-5c2e-11e9-8a57-e63f2114e204.png)

**Comment by jeff-hykin** [comment]
Thanks this should be fixed in `v1.7.6`
