### ISSUE TITLE
Create and Agree on a Comprehensive Tagging Standard

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/cpp-textmate-grammar#86]
The standard originally established by TextMate was a decent first attempt.
https://macromates.com/manual/en/language_grammars#naming_conventions

However, it is a far cry from being comprehensive and even worse there are situations where pieces of languages do not fall under any category. For example tags such as `entity` and `variable` start to completely break down in some languages like Javascript where a 'variable' can be a function (one kind of `entity`) and class (another kind of `entity`) and a primitive value (`variable`).

This is an issue on this repo because its hard to even stay consistent only within C++. A system needs to be made for at least this repo, and whatever standard is decided upon, I'd like it to be applicable to all languages. Even very strange languages such as `AsciiDots` or `Befunge`.

Goals:
  * Maintain backwards compatibility
  * Be language agnostic
  * Easy for theme makers to utilize
    * minimize edge cases
    * have reusable concepts
    * have a centralized listing of all possible names
  * Have at least one, and preferably only one, way of tagging any concept
  * Does not require tags to be in a hierarchy
  * Open to the public to change/update
    * If one person adds a custom tag for his language concept, the public repo sees that and can use that same name
  * Be a standard even if using a non-TextMate parser

TextMate has support for scope selectors
https://macromates.com/manual/en/scope_selectors
Which are incredibly useful, but they are not used very frequently.

The major concept I'd like to discuss is to switch tags to be used as key-value pairs rather than a specificity chain. 
For example:
The `and` operator could have
* `name-is.and`
* `a-kind-of.keyword`
* `a-kind-of.operator`
* `has-property.and`
* `has-property.logical`
* `has-property.alias`

The `this` keyword could have 
* `name-is.this`
* `a-kind-of.keyword`
* `a-kind-of.variable`
* `a-kind-of.object`
* `has-property.pointer`

The `&` operator could have
* `symbol-is.Ampersand` 'Ampersand' being the unicode name of the symbol
* `a-kind-of.operator`
* `has-property.and`
* `has-property.bitwise`
* `has-property.logical`

The `&&` operator could have
* `symbol-is.Ampersand--Ampersand`
* `a-kind-of.operator`
* `has-property.and`
* `has-property.logical`

Rough sketch of potential standard keys
* `name-is` if the token has a specific name (mostly for keywords)
* `symbol-is` the characters that compose the token, written in Unicode separated with a double dash
* `is-like` things that are not strictly true statements, but would be true from the perspective of general cross-language concepts
* `locally-is` qualities the token has that are concepts or names local to that language (normally spec-compliant names)
* `part-of` the token is an essential peice in a larger pattern
* `meta` the token encapsulates other independent tokens

This is still just a idea.

Reminder to self: explore the idea of a 'joiner' tag for practical reasons.

**Comment by matter123** [comment]
My initial concern for key-value pairs is that TextMate scopes are inherently hierarchical.

If a theme has `a-kind-of.operator has-property.logical` It won't match `&&` which has those backwards.

**Comment by jeff-hykin** [comment]
True that is the major flaw. Whatever terms we create would have to be sorted in some way. Either manually or by a process like alphabetically.

**Comment by jeff-hykin** [comment]
I wish we could just use CSS classes instead.

**Comment by matter123** [comment]
Vscode used to use css classes prior to 1.9 https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations

**Comment by jeff-hykin** [comment]
That was an awesome link, thanks for sharing that. That's really sad about not being able to use CSS though. I wish we could implement a pseudo CSS standard that could still keep the optimizations.

I didn't realize how deeply invested VS Code is in TextMate Syntaxes. It is actually kind of concerning. If find a similar article about how sublime or Atom do parsing I would definitely want to know how they do it.

**Comment by jeff-hykin** [comment]
That is a cool video, I hadn't seen the newer one. Sadly its not exactly what we're looking for on this issue though.

**Comment by jeff-hykin** [comment]
@matter123  I've been exploring this a bit more and I think it'll work given a few caveats. The `textmate_tools.rb` can handle things pretty easily from the syntax side, we just give it the attributes and it will sort them when the grammar gets generated. I'll probably implement that sometime in the summer. All of the existing TextMate names can be ported into the new style and that'll give it a solid foundation.

The hard part is going to be the Themer's side. Either there's going to need to be a tool for auto-sorting the attributes for them, or VS Code is going to need to implement something on there side. It wouldn't be difficult though, it would just be a Javascript array attribute that gets sorted before becoming a string, so if I can find the code for the `editor.tokenColorCustomizations: { textMateRules: }` I can probably make a PR for it once the rest of it is ready.

It'll probably take a 2 months of casual work, but it's going to be needed even after the switch to the tree sitter.

**Comment by matter123** [comment]
How would vscode auto sorting tell `source.cpp meta.block.cpp numeric.constant.cpp` which should be sorted from `is-like.block symbol-is.numeric has-property.constant` which should be sorted?

**Comment by jeff-hykin** [comment]
lets say this order:
```
name-is.[ alpha-numeric sub sorting]
symbol-is.[ alpha-numeric sub sorting] 
is-like.[ alpha-numeric sub sorting]
locally-is.[ alpha-numeric sub sorting]
part-of.[ alpha-numeric sub sorting]
has-property.[ alpha-numeric sub sorting]
```

The sorting would be done local to the newPattern(), and then each local sorting would be separated by `meta`'s. Pretty much only meta's should be nesting anyways.

So for a constructor inside a struct the inspect TM scopes might look like

`source.cpp is-like.class-body.cpp meta.block.struct.cpp is-like.constructor.cpp is-like.function.cpp is-locally.constructor.cpp meta.block.constructor.cpp`

For a themer or a VS Code auto thing, you'd give it an array like [ 'is-like.function', 'is-like.constructor.cpp' ] and it would meta-separate it and then sort the individual separations. e.g. [ 'is-like.constructor.cpp', 'is-like.function' ].

I guess it would be good to make it clear on the VS Code side that is was going to separate it by meta's .

**Comment by matter123** [comment]
My point is vscode has grammars that need to be shared across editors, fo example is the information for contributers is to believed, the markdown grammar is still based on the tmBundle. Any progress changing vscode sorting order needs to accommodate hierarchical Scopes and those can't be sorted.

**Comment by jeff-hykin** [comment]
Hmm I don't quite follow. The existing hierarchy would be maintained, it would only be the non-standard TM scopes that would be sorted, and they would be placed inbetween ("injected") into the existing hierarchy.

The only thing that would be sorted is the individual injections.

If the old tags were
`1 2 3`

And an theme used `2 3`

The new tags would be 
`[sorted stuff] 1 [sorted stuff] 2 [sorted stuff ] 3`

The theme's `2 3` pattern will still match so backwards compatibly would be maintained.

**Comment by jeff-hykin** [comment]
I'm going to close this. I think the TextMate scope selectors will probably have to be made due with. 

I hope to pick this issue back up with the Tree Sitter, and create a new standard as part of it.
