### ISSUE TITLE
#endif not always not being tokenized correctly

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#88]
From https://github.com/Microsoft/vscode/issues/72096

Looks like the #endif in this case is categorized incorrectly as:
meta.head.struct.cpp
meta.block.struct.cpp
source.cpp

```
// .h file with C++ syntax highlighting
#ifdef USE_IN_HLSL
cbuffer  testCB
#else
struct testCB
#endif   // <= this #endif is highlighted white although its valid
{
  float Brightness;
  // ...
};
// the .h file with this struct definition can be used in HLSL and in C++ code 
// this way
```

![endif_syntax_highlighting](https://user-images.githubusercontent.com/28405357/55911714-762de800-5be1-11e9-9074-d20088bfc020.jpg)

**Comment by jeff-hykin** [comment]
This was a quick fix, pushed with v1.7.7
