### ISSUE TITLE
Incorrect syntax highlighting when types contain other types within them

### ISSUE THREAD

**Issue by tristan957** [jeff-hykin/cpp-textmate-grammar#95]
![image](https://user-images.githubusercontent.com/11936772/56089390-ae3e6080-5e57-11e9-87e2-910785c3de75.png)

**Comment by matter123** [comment]
Is this with 1.7.7? I cannot reproduce.
![Screenshot from 2019-04-13 23-57-16](https://user-images.githubusercontent.com/714007/56089462-04a3a300-5e48-11e9-83c6-3d851622a64d.png)

**Comment by jeff-hykin** [comment]
It's a C issue.

**Comment by matter123** [comment]
Ok created PR.

**Comment by jeff-hykin** [comment]
fix pushed with `v1.8.0`

**Comment by tristan957** [comment]
Solid :+1: thanks
