### ISSUE TITLE
Numbers in embedded cpp markdown are not highlighted 

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/cpp-textmate-grammar#97]
This is inside of a markdown document.

<img width="464" alt="Screen Shot 2019-04-14 at 6 12 44 PM" src="https://user-images.githubusercontent.com/17692058/56100644-07060b80-5ee1-11e9-83d9-0eb955daff91.png">
There is this intersting issue where numbers are not tagged. 

```
newPattern(
            match: /\b\d+\b/,
            tag_as: "constant.numeric"
        ),
```

Adding the pattern^ above the full number pattern actually fixes the issue (but it obviously breaks the complex number matching). My guess is that the number pattern is timing out, which I find surprising. The pattern is really long, but it should be able to match a two digit number in a very short amount of time. I'm also not exactly sure why it behaves different when it is embedded.

**Comment by matter123** [comment]
Does embedded actually use the extension or does it use the default (1.4.5 1.33.0, atom/language-c 1.33.1, 1.7.6 insiders)?

**Comment by jeff-hykin** [comment]
Thankfully it uses the extension.

**Comment by matter123** [comment]
It looks significantly worse for me.
![Screenshot from 2019-04-14 16-24-39](https://user-images.githubusercontent.com/714007/56100787-e1253a80-5ed1-11e9-8de2-a73eee814217.png)

**Comment by jeff-hykin** [comment]
Yeah, pull from master I push pushed a large fix that was thanks to replacing all instances of `$base`

**Comment by jeff-hykin** [comment]
The issue with `$base` is that it is dynamic, it actually re-includes everything in the markup language, when really we wanted it to only be C++

**Comment by matter123** [comment]
Why was `#cpp_base` chosen over `$self`?

**Comment by jeff-hykin** [comment]
I believe that `$self` references the current pattern (so its like recursion) but `$base` always goes to the root most pattern.

**Comment by matter123** [comment]
I am fairly sure that is incorrect.

From https://macromates.com/manual/en/language_grammars
> To reference the grammar itself, use $self:

Additionally using $self
![Screenshot from 2019-04-14 17-05-02](https://user-images.githubusercontent.com/714007/56101321-7b3bb180-5ed7-11e9-8a56-e5e04daf3710.png)

**Comment by jeff-hykin** [comment]
oops, yup looks like we should switch to using `$self`. That is a terribly unintuitive naming scheme, good catch on your part though. I'm out of time for today, but the next change I do will probably be that.

The C grammar still needs the fix.

**Comment by matter123** [comment]
I can switch both to self in an hour or so.

**Comment by matter123** [comment]
Here is the vscode-textmate's `inspect` tool output for line 6 of example.md https://gist.github.com/matter123/fd7fbb3d2fd575208fb872058dc98b60.

And for the simple pattern https://gist.github.com/matter123/63ad7294e30926ad254ccfe84bc932e4

**Comment by matter123** [comment]
This is fixed by https://github.com/Microsoft/vscode-textmate/pull/88

**Comment by jeff-hykin** [comment]
Thanks for looking into this so deeply. Thats a really nice `inspect` tool. I'll rename this issue so that people can find it easier.

**Comment by matter123** [comment]
vscode-textmate/#88 was merged in today. I'll close this as soon as insiders has the new version, and I confirm its fixed.

**Comment by jeff-hykin** [comment]
Great, that means we can probably move forward with the almoat-perfect preprocessor conditional pattern for #31

**Comment by matter123** [comment]
With
```
Version: 1.37.0-insider
Commit: 894056d11c7fffb261a0100fd4dcbf8cff84a8c0
Date: 2019-07-15T05:25:26.901Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.0-gentoo snap
```
The numbers have correct highlighting.
