### ISSUE TITLE
pthread types look like they should be support.type.pthread.cpp

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#99]
https://github.com/jeff-hykin/cpp-textmate-grammar/blob/master/syntaxes/cpp.tmLanguage.yaml#L821

````cpp
    pthread_rwlockattr_t thing;
````

Currently `pthread_rwlockattr_t` above is storage.type.cpp. Based on the syntax, it looks like it's intended to be support.type.pthread.cpp. In the old text mate grammar, it would have been support.type.pthread.c.

It looks like I can safely change the VS Code themes to use storage.type.cpp. Before I do, is that the intended value?

**Comment by matter123** [comment]
No `storage.type.cpp` is not the intended value. As [Line 1559](https://github.com/jeff-hykin/cpp-textmate-grammar/blob/master/cpp/generate.rb#L1559) shows, the intended scope is `support.type.pthread.cpp`.
